// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: CompassPage

#include "../ui.h"

lv_obj_t * ui_CompassPage = NULL;
lv_obj_t * ui_CompassPageImg = NULL;
lv_obj_t * ui_CompassAngleBtn = NULL;
lv_obj_t * ui_AngleIconLabel = NULL;
lv_obj_t * ui_AngelColonIcon = NULL;
lv_obj_t * ui_AngelNum = NULL;
lv_obj_t * ui_CompassAltitudeBtn = NULL;
lv_obj_t * ui_AltitudeIconLabel = NULL;
lv_obj_t * ui_AltitudeColonIcon = NULL;
lv_obj_t * ui_AltitudeNum = NULL;
// event funtions

// build funtions

void ui_CompassPage_screen_init(void)
{
    ui_CompassPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CompassPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CompassPageImg = lv_image_create(ui_CompassPage);
    lv_image_set_src(ui_CompassPageImg, &ui_img_compass_needle_png);
    lv_obj_set_width(ui_CompassPageImg, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_CompassPageImg, LV_SIZE_CONTENT);    /// 171
    lv_obj_set_align(ui_CompassPageImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompassPageImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_CompassPageImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CompassAngleBtn = lv_button_create(ui_CompassPage);
    lv_obj_set_width(ui_CompassAngleBtn, 100);
    lv_obj_set_height(ui_CompassAngleBtn, 30);
    lv_obj_set_x(ui_CompassAngleBtn, -60);
    lv_obj_set_y(ui_CompassAngleBtn, 120);
    lv_obj_set_align(ui_CompassAngleBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompassAngleBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CompassAngleBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompassAngleBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompassAngleBtn, lv_color_hex(0x4A4C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassAngleBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AngleIconLabel = lv_label_create(ui_CompassAngleBtn);
    lv_obj_set_width(ui_AngleIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AngleIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AngleIconLabel, -30);
    lv_obj_set_y(ui_AngleIconLabel, 0);
    lv_obj_set_align(ui_AngleIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AngleIconLabel, "");
    lv_obj_set_style_text_font(ui_AngleIconLabel, &ui_font_CPiconfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AngelColonIcon = lv_label_create(ui_CompassAngleBtn);
    lv_obj_set_width(ui_AngelColonIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AngelColonIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AngelColonIcon, -12);
    lv_obj_set_y(ui_AngelColonIcon, -2);
    lv_obj_set_align(ui_AngelColonIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AngelColonIcon, ":");
    lv_obj_set_style_text_font(ui_AngelColonIcon, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AngelNum = lv_label_create(ui_CompassAngleBtn);
    lv_obj_set_width(ui_AngelNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AngelNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AngelNum, 25);
    lv_obj_set_y(ui_AngelNum, 0);
    lv_obj_set_align(ui_AngelNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AngelNum, "360°");
    lv_obj_set_style_text_font(ui_AngelNum, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassAltitudeBtn = lv_button_create(ui_CompassPage);
    lv_obj_set_width(ui_CompassAltitudeBtn, 100);
    lv_obj_set_height(ui_CompassAltitudeBtn, 30);
    lv_obj_set_x(ui_CompassAltitudeBtn, 60);
    lv_obj_set_y(ui_CompassAltitudeBtn, 120);
    lv_obj_set_align(ui_CompassAltitudeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompassAltitudeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CompassAltitudeBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompassAltitudeBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompassAltitudeBtn, lv_color_hex(0x4A4C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassAltitudeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeIconLabel = lv_label_create(ui_CompassAltitudeBtn);
    lv_obj_set_width(ui_AltitudeIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeIconLabel, -30);
    lv_obj_set_y(ui_AltitudeIconLabel, 0);
    lv_obj_set_align(ui_AltitudeIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeIconLabel, "");
    lv_obj_set_style_text_font(ui_AltitudeIconLabel, &ui_font_CPiconfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeColonIcon = lv_label_create(ui_CompassAltitudeBtn);
    lv_obj_set_width(ui_AltitudeColonIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeColonIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeColonIcon, 19);
    lv_obj_set_y(ui_AltitudeColonIcon, 0);
    lv_obj_set_align(ui_AltitudeColonIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeColonIcon, "0m");
    lv_obj_set_style_text_font(ui_AltitudeColonIcon, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeNum = lv_label_create(ui_CompassAltitudeBtn);
    lv_obj_set_width(ui_AltitudeNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeNum, -12);
    lv_obj_set_y(ui_AltitudeNum, -2);
    lv_obj_set_align(ui_AltitudeNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeNum, ":");
    lv_obj_set_style_text_font(ui_AltitudeNum, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_CompassPage_screen_destroy(void)
{
    if(ui_CompassPage) lv_obj_del(ui_CompassPage);

    // NULL screen variables
    ui_CompassPage = NULL;
    ui_CompassPageImg = NULL;
    ui_CompassAngleBtn = NULL;
    ui_AngleIconLabel = NULL;
    ui_AngelColonIcon = NULL;
    ui_AngelNum = NULL;
    ui_CompassAltitudeBtn = NULL;
    ui_AltitudeIconLabel = NULL;
    ui_AltitudeColonIcon = NULL;
    ui_AltitudeNum = NULL;

}
