// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: AboutPage

#include "ui_AboutPage.h"

lv_obj_t * ui_AboutPage = NULL;
lv_obj_t * ui_NameLabel = NULL;
lv_obj_t * ui_NameTextLabel = NULL;
lv_obj_t * ui_VersionLabel = NULL;
lv_obj_t * ui_VersionTextLabel = NULL;
lv_obj_t * ui_MCULabel = NULL;
lv_obj_t * ui_MCUTextLabel = NULL;
lv_obj_t * ui_OSLabel = NULL;
lv_obj_t * ui_OSTextLabel = NULL;
lv_obj_t * ui_UILabel = NULL;
lv_obj_t * ui_UITextLabel = NULL;

// event funtions
static void about_page_event_cb(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_GESTURE)
    {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
        {
            page_back();
        }
    }
}

// build funtions
void ui_AboutPage_screen_init(void)
{
    ui_AboutPage = lv_obj_create(NULL);

    ui_NameLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_NameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameLabel, 10);
    lv_obj_set_y(ui_NameLabel, 10);
    lv_label_set_text(ui_NameLabel, "手表型号");
    lv_obj_set_style_text_color(ui_NameLabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_NameTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTextLabel, 15);
    lv_obj_set_y(ui_NameTextLabel, 35);
    lv_label_set_text(ui_NameTextLabel, "SWatch");
    lv_obj_set_style_text_font(ui_NameTextLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_VersionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionLabel, 10);
    lv_obj_set_y(ui_VersionLabel, 60);
    lv_label_set_text(ui_VersionLabel, "固件版本");
    lv_obj_set_style_text_color(ui_VersionLabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VersionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VersionLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionTextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_VersionTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionTextLabel, 15);
    lv_obj_set_y(ui_VersionTextLabel, 85);
    lv_label_set_text(ui_VersionTextLabel, "V1.0.0");
    lv_obj_set_style_text_font(ui_VersionTextLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MCULabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_MCULabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MCULabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MCULabel, 10);
    lv_obj_set_y(ui_MCULabel, 110);
    lv_label_set_text(ui_MCULabel, "主控芯片");
    lv_obj_set_style_text_color(ui_MCULabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MCULabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MCULabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MCUTextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_MCUTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MCUTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MCUTextLabel, 15);
    lv_obj_set_y(ui_MCUTextLabel, 135);
    lv_label_set_text(ui_MCUTextLabel, "STM32F411CEU6");
    lv_obj_set_style_text_font(ui_MCUTextLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OSLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_OSLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OSLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OSLabel, 10);
    lv_obj_set_y(ui_OSLabel, 160);
    lv_label_set_text(ui_OSLabel, "操作系统");
    lv_obj_set_style_text_color(ui_OSLabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OSLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OSLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OSTextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_OSTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OSTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OSTextLabel, 15);
    lv_obj_set_y(ui_OSTextLabel, 185);
    lv_label_set_text(ui_OSTextLabel, "FreeRTOS");
    lv_obj_set_style_text_font(ui_OSTextLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UILabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_UILabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UILabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UILabel, 10);
    lv_obj_set_y(ui_UILabel, 210);
    lv_label_set_text(ui_UILabel, "图形界面");
    lv_obj_set_style_text_color(ui_UILabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UILabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UILabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UITextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_UITextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UITextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UITextLabel, 15);
    lv_obj_set_y(ui_UITextLabel, 235);
    lv_label_set_text(ui_UITextLabel, "LVGL");
    lv_obj_set_style_text_font(ui_UITextLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AboutPage,about_page_event_cb,LV_EVENT_GESTURE,NULL);
}

void ui_AboutPage_screen_destroy(void)
{
    if(ui_AboutPage) lv_obj_del(ui_AboutPage);

    // NULL screen variables
    ui_AboutPage = NULL;
    ui_NameLabel = NULL;
    ui_NameTextLabel = NULL;
    ui_VersionLabel = NULL;
    ui_VersionTextLabel = NULL;
    ui_MCULabel = NULL;
    ui_MCUTextLabel = NULL;
    ui_OSLabel = NULL;
    ui_OSTextLabel = NULL;
    ui_UILabel = NULL;
    ui_UITextLabel = NULL;

}


static void about_page_init()
{
	ui_AboutPage_screen_init();
}

static void about_page_deinit()
{
	ui_AboutPage_screen_destroy();
}

static void about_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void about_page_pause()
{
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_about = 
{
	.page_obj = &ui_AboutPage,
	.init = about_page_init,
	.deinit = about_page_deinit,
	.resume = about_page_resume,
	.pause = about_page_pause,
};
