// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: testpage

#include "ui_ChargePage.h"
#include "ui_HomePage.h"
#include "hw_interface.h"

lv_obj_t * ui_ChargePage = NULL;
lv_obj_t * ui_ChargPageBatNum = NULL;
lv_obj_t * ui_ChargPagebHourLabel = NULL;
lv_obj_t * ui_ChargPagebMinLabel = NULL;
lv_obj_t * ui_ChargPageTimePoint = NULL;
lv_obj_t * ui_CharPageBatArc = NULL;
lv_obj_t * ui_ChargPageBatIcon = NULL;
// event funtions

lv_timer_t * ui_ChargePageTimer = NULL;

// static void charge_page_event_cb(lv_event_t* e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);

//     if(event_code == LV_EVENT_GESTURE)
//     {
//         lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
//         if(dir == LV_DIR_RIGHT)
//         {
//             page_back();
//         }
//     }
// }

static void charge_page_timer_cb(lv_timer_t * timer)
{

    if(get_top_page()->page_obj == &ui_ChargePage) // 仅在ChargePage位于页面栈顶时更新显示
    {
        uint8_t buffer[5];

        hw_date_time_t date_time;
        hw_interface.hw_rtc_interface->get_time_date(&date_time); // 从RTC获取当前时间日期

        if(ui_TimeHourValue != date_time.hours) // 仅在时间发生变化时更新显示，避免不必要的刷新
        {
            ui_TimeHourValue = date_time.hours;
			sprintf(buffer,"%02d",ui_TimeHourValue);
			lv_label_set_text(ui_ChargPagebMinLabel, buffer);
        }

        if(ui_TimeMinuteValue != date_time.minutes) // 仅在时间发生变化时更新显示，避免不必要的刷新
        {
            ui_TimeMinuteValue = date_time.minutes;
            sprintf(buffer,"%02d",ui_TimeMinuteValue);
            lv_label_set_text(ui_ChargPagebMinLabel, buffer);
        }

        ui_BatArcValue = hw_interface.hw_power_interface->bat_caluculate();
        if(ui_BatArcValue >0 && ui_BatArcValue <= 100)
        {
            lv_arc_set_value(ui_CharPageBatArc, ui_BatArcValue); // 更新电量圆弧显示
            sprintf(buffer, "%d%%",ui_BatArcValue);
            lv_label_set_text(ui_ChargPageBatNum, buffer); // 更新电量百分比显示   
        }
        else
        {
            ui_BatArcValue = 0;
        }
    }
 
}

// build funtions

void ui_ChargePage_screen_init(void)
{
    uint8_t buffer[5];

    ui_ChargePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ChargePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChargPageBatNum = lv_label_create(ui_ChargePage);
    lv_obj_set_width(ui_ChargPageBatNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPageBatNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargPageBatNum, -70);
    lv_obj_set_y(ui_ChargPageBatNum, -23);
    lv_obj_set_align(ui_ChargPageBatNum, LV_ALIGN_CENTER);
    sprintf((char*)buffer, "%d%%",ui_BatArcValue);
    lv_label_set_text(ui_ChargPageBatNum, buffer); // 初始电量百分比显示
    lv_obj_set_style_text_color(ui_ChargPageBatNum, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPageBatNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPageBatNum, &ui_font_CuYuan30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargPagebHourLabel = lv_label_create(ui_ChargePage);
    lv_obj_set_width(ui_ChargPagebHourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPagebHourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargPagebHourLabel, 59);
    lv_obj_set_y(ui_ChargPagebHourLabel, -73);
    lv_obj_set_align(ui_ChargPagebHourLabel, LV_ALIGN_CENTER);
    sprintf((char*)buffer, "%02d",ui_TimeHourValue);
    lv_label_set_text(ui_ChargPagebHourLabel,buffer); // 初始小时显示
    lv_obj_set_style_text_color(ui_ChargPagebHourLabel, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPagebHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPagebHourLabel, &ui_font_OpenSasnsItalic100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ChargPagebHourLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChargPagebHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChargPagebHourLabel, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargPagebMinLabel = lv_label_create(ui_ChargePage);
    lv_obj_set_width(ui_ChargPagebMinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPagebMinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargPagebMinLabel, 56);
    lv_obj_set_y(ui_ChargPagebMinLabel, 44);
    lv_obj_set_align(ui_ChargPagebMinLabel, LV_ALIGN_CENTER);
    sprintf((char*)buffer, "%02d",ui_TimeMinuteValue);
    lv_label_set_text(ui_ChargPagebMinLabel, buffer); // 初始分钟显示
    lv_obj_set_style_text_color(ui_ChargPagebMinLabel, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPagebMinLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPagebMinLabel, &ui_font_OpenSasnsItalic100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargPageTimePoint = lv_label_create(ui_ChargePage);
    lv_obj_set_width(ui_ChargPageTimePoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPageTimePoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargPageTimePoint, -24);
    lv_obj_set_y(ui_ChargPageTimePoint, 37);
    lv_obj_set_align(ui_ChargPageTimePoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargPageTimePoint, ":");
    lv_obj_set_style_text_color(ui_ChargPageTimePoint, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPageTimePoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPageTimePoint, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharPageBatArc = lv_arc_create(ui_ChargePage);
    lv_obj_set_width(ui_CharPageBatArc, 60);
    lv_obj_set_height(ui_CharPageBatArc, 60);
    lv_obj_set_x(ui_CharPageBatArc, -70);
    lv_obj_set_y(ui_CharPageBatArc, -75);
    lv_obj_set_align(ui_CharPageBatArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CharPageBatArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_CharPageBatArc, ui_BatArcValue); // 初始电量显示
    lv_arc_set_bg_angles(ui_CharPageBatArc, 90, 440);
    lv_obj_set_style_arc_width(ui_CharPageBatArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_CharPageBatArc, lv_color_hex(0x00FF7F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CharPageBatArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CharPageBatArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CharPageBatArc, lv_color_hex(0x00FF7F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CharPageBatArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CharPageBatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CharPageBatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CharPageBatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CharPageBatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ChargPageBatIcon = lv_label_create(ui_CharPageBatArc);
    lv_obj_set_width(ui_ChargPageBatIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPageBatIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChargPageBatIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargPageBatIcon, "");
    lv_obj_set_style_text_color(ui_ChargPageBatIcon, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPageBatIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPageBatIcon, &ui_font_HPiconfont25, LV_PART_MAIN | LV_STATE_DEFAULT);

    //lv_obj_add_event_cb(ui_ChargePage, charge_page_event_cb, LV_EVENT_GESTURE, NULL); // 注册事件回调
}

void ui_ChargePage_screen_destroy(void)
{
    if(ui_ChargePage) lv_obj_del(ui_ChargePage);

    // NULL screen variables
    ui_ChargePage = NULL;
    ui_ChargPageBatNum = NULL;
    ui_ChargPagebHourLabel = NULL;
    ui_ChargPagebMinLabel = NULL;
    ui_ChargPageTimePoint = NULL;
    ui_CharPageBatArc = NULL;
    ui_ChargPageBatIcon = NULL;

}

static void charge_page_init()
{
    ui_ChargePage_screen_init();
}

static void charge_page_deinit()
{
    ui_ChargePage_screen_destroy();
}

static void charge_page_resume()
{
    if(ui_ChargePageTimer == NULL){
        ui_ChargePageTimer = lv_timer_create(charge_page_timer_cb, 2000, NULL); // 创建定时器，每秒更新一次
    }
    // 页面恢复时刷新显示（如有需要可在此读取电量并更新控件）
}

static void charge_page_pause()
{
    if(ui_ChargePageTimer) {
        lv_timer_del(ui_ChargePageTimer); // 删除定时器
        ui_ChargePageTimer = NULL;
    }
    // 页面暂停时保存状态或停止定时器
}

page_t page_charge =
{
    .page_obj = &ui_ChargePage,
    .init = charge_page_init,
    .deinit = charge_page_deinit,
    .resume = charge_page_resume,
    .pause = charge_page_pause,
};

