// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: CompassPage

#include "ui_CompassPage.h"
#include "hw_interface.h"
#include "user_sensor_task.h"

lv_obj_t * ui_CompassPage = NULL;
lv_obj_t * ui_CompassPageImg = NULL;
lv_obj_t * ui_CompassAngleBtn = NULL;
lv_obj_t * ui_AngleIconLabel = NULL;
lv_obj_t * ui_AngelColonIcon = NULL;
lv_obj_t * ui_AngelNum = NULL;
lv_obj_t * ui_CompassAltitudeBtn = NULL;
lv_obj_t * ui_AltitudeIconLabel = NULL;
lv_obj_t * ui_AltitudeColonIcon = NULL;
lv_obj_t * ui_ui_AltitudeNum = NULL;

lv_obj_t * compass_scale = NULL;

lv_timer_t* ui_CompassPageTimer = NULL;

// event funtions

static void compass_page_event_cb(lv_event_t* e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_GESTURE)
	{
			lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
			if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
            {
				 page_back();
            }
	}
}

static void compass_page_timer_cb(lv_timer_t* timer)
{
    uint8_t disp_buffer[6];

    // 电子指南针指向设置，以及显示当前方向角度值
    lv_image_set_rotation(ui_CompassPageImg,hw_interface.hw_ecompass_interface->direction * 10); // 原来的lv_img_set_angle()函数在lvgl 9.0后替换成了这个
    sprintf(disp_buffer, "%d", hw_interface.hw_ecompass_interface->direction);
    lv_label_set_text(ui_AngelNum, disp_buffer);

    // 显示海拔
    sprintf(disp_buffer,"%dm", hw_interface.hw_barometer_interface->altitude);
    lv_label_set_text(ui_AltitudeColonIcon, disp_buffer);

    sensor_msg_t msg = MSG_COMPASS_MEASURE;
	osMessageQueuePut(SensorMsgQueue, &msg, NULL, 0); 
}

// build funtions

void ui_CompassPage_screen_init(void)
{
    ui_CompassPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CompassPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    /* 手动实现刻度盘*/
    compass_scale = lv_scale_create(ui_CompassPage);
    lv_obj_set_size(compass_scale, 240, 240);
    lv_obj_align(compass_scale, LV_ALIGN_TOP_MID, 0, 2); // 刻度为顶部居中

    // 设置圆弧样式：隐藏主弧线与外圈（去掉刻度形成的“白圈”）
    lv_obj_set_style_arc_width(compass_scale, 0, LV_PART_MAIN); // 主弧线宽度为0
    lv_obj_set_style_arc_opa(compass_scale, LV_OPA_TRANSP, LV_PART_MAIN); // 透明度：主弧线透明
    lv_obj_set_style_border_width(compass_scale, 0, LV_PART_MAIN); // 无边框 
    lv_obj_set_style_outline_opa(compass_scale, LV_OPA_TRANSP, LV_PART_MAIN); // 无轮廓
    lv_obj_set_style_shadow_opa(compass_scale, LV_OPA_TRANSP, LV_PART_MAIN); // 无阴影

    // 设置刻度盘样式:LV_PART_MAIN
    lv_obj_set_style_bg_opa(compass_scale, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_bg_color(compass_scale, lv_color_hex(0x292831), LV_PART_MAIN); //灰色背景
    lv_obj_set_style_radius(compass_scale, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    lv_obj_set_style_clip_corner(compass_scale, true, LV_PART_MAIN); // 圆角裁剪
    lv_obj_set_style_pad_all(compass_scale, 10, LV_PART_MAIN); // 圆向外填充，使刻度线不贴近

    // 刻度线在内部
    lv_scale_set_mode(compass_scale, LV_SCALE_MODE_ROUND_INNER);

    // 刻度设置：61个刻度，12个主刻度
    lv_scale_set_total_tick_count(compass_scale, 61);   // 设置刻度总数(大小刻度都包括)：0..60,共61个刻度
    lv_scale_set_major_tick_every(compass_scale, 5);  // 每5个刻度一个主刻度
    lv_scale_set_label_show(compass_scale, true);      // 刻度显示数字
    lv_scale_set_angle_range(compass_scale, 360);       // 全圆
    lv_scale_set_rotation(compass_scale, 270);          // 从 12 点方向开始（0° 在正上方）
    
    static const char * compass_labels[] = {"0", "30", "60", "90", "120", "150", "180", "210", "240", "270", "300", "330", NULL};
    lv_scale_set_text_src(compass_scale, compass_labels); // 修改12个主刻度标签的值分别为 0..330

    // 刻度线样式：
    // 设置非主刻度(minor)使用 LV_PART_ITEMS
    lv_obj_set_style_line_color(compass_scale, lv_color_white(), LV_PART_ITEMS);
    lv_obj_set_style_line_width(compass_scale, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_opa(compass_scale, LV_OPA_COVER, LV_PART_ITEMS);
    lv_obj_set_style_length(compass_scale, 10, LV_PART_ITEMS);

    // 设置主刻度(major)在 LVGL v9 使用 LV_PART_INDICATOR
    lv_obj_set_style_line_color(compass_scale, lv_color_white(), LV_PART_INDICATOR);
    lv_obj_set_style_line_width(compass_scale, 2, LV_PART_INDICATOR);
    lv_obj_set_style_line_opa(compass_scale, LV_OPA_COVER, LV_PART_INDICATOR);
    lv_obj_set_style_length(compass_scale, 15, LV_PART_INDICATOR);
    
    ui_CompassPageImg = lv_image_create(compass_scale);
    lv_image_set_src(ui_CompassPageImg, &ui_img_compass_needle_png);
    lv_obj_set_width(ui_CompassPageImg, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_CompassPageImg, LV_SIZE_CONTENT);    /// 171
    lv_obj_set_align(ui_CompassPageImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompassPageImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_CompassPageImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CompassAngleBtn = lv_button_create(ui_CompassPage);
    lv_obj_set_width(ui_CompassAngleBtn, 100);
    lv_obj_set_height(ui_CompassAngleBtn, 30);
    lv_obj_set_x(ui_CompassAngleBtn, -60);
    lv_obj_set_y(ui_CompassAngleBtn, 120);
    lv_obj_set_align(ui_CompassAngleBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompassAngleBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CompassAngleBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompassAngleBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompassAngleBtn, lv_color_hex(0x4a4c52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassAngleBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AngleIconLabel = lv_label_create(ui_CompassAngleBtn);
    lv_obj_set_width(ui_AngleIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AngleIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AngleIconLabel, -30);
    lv_obj_set_y(ui_AngleIconLabel, 0);
    lv_obj_set_align(ui_AngleIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AngleIconLabel, "\xEE\x98\x8A"); // 这里使用转移字符输出UTF-8编码，不知道为什么字符显示不出来
    lv_obj_set_style_text_font(ui_AngleIconLabel, &ui_font_CPiconfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
		
    ui_AngelColonIcon = lv_label_create(ui_CompassAngleBtn);
    lv_obj_set_width(ui_AngelColonIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AngelColonIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AngelColonIcon, -12);
    lv_obj_set_y(ui_AngelColonIcon, -2);
    lv_obj_set_align(ui_AngelColonIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AngelColonIcon, ":");
    lv_obj_set_style_text_font(ui_AngelColonIcon, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AngelNum = lv_label_create(ui_CompassAngleBtn);
    lv_obj_set_width(ui_AngelNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AngelNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AngelNum, 25);
    lv_obj_set_y(ui_AngelNum, 0);
    lv_obj_set_align(ui_AngelNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AngelNum, "360°");
    lv_obj_set_style_text_font(ui_AngelNum, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassAltitudeBtn = lv_button_create(ui_CompassPage);
    lv_obj_set_width(ui_CompassAltitudeBtn, 100);
    lv_obj_set_height(ui_CompassAltitudeBtn, 30);
    lv_obj_set_x(ui_CompassAltitudeBtn, 60);
    lv_obj_set_y(ui_CompassAltitudeBtn, 120);
    lv_obj_set_align(ui_CompassAltitudeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompassAltitudeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CompassAltitudeBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompassAltitudeBtn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompassAltitudeBtn, lv_color_hex(0x4a4c52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassAltitudeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeIconLabel = lv_label_create(ui_CompassAltitudeBtn);
    lv_obj_set_width(ui_AltitudeIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeIconLabel, -30);
    lv_obj_set_y(ui_AltitudeIconLabel, 0);
    lv_obj_set_align(ui_AltitudeIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeIconLabel, "\xEE\x98\xB4"); //这里使用转移字符输出UTF-8编码，不知道为什么字符显示不出来
    lv_obj_set_style_text_font(ui_AltitudeIconLabel, &ui_font_CPiconfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeColonIcon = lv_label_create(ui_CompassAltitudeBtn);
    lv_obj_set_width(ui_AltitudeColonIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeColonIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AltitudeColonIcon, 19);
    lv_obj_set_y(ui_AltitudeColonIcon, 0);
    lv_obj_set_align(ui_AltitudeColonIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeColonIcon, "0m");
    lv_obj_set_style_text_font(ui_AltitudeColonIcon, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ui_AltitudeNum = lv_label_create(ui_CompassAltitudeBtn);
    lv_obj_set_width(ui_ui_AltitudeNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ui_AltitudeNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ui_AltitudeNum, -12);
    lv_obj_set_y(ui_ui_AltitudeNum, -2);
    lv_obj_set_align(ui_ui_AltitudeNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ui_AltitudeNum, ":");
    lv_obj_set_style_text_font(ui_ui_AltitudeNum, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

	lv_obj_add_event_cb(ui_CompassPage,compass_page_event_cb,LV_EVENT_GESTURE,NULL);
}

void ui_CompassPage_screen_destroy(void)
{
    if(ui_CompassPage) lv_obj_del(ui_CompassPage);

    // NULL screen variables
    ui_CompassPage = NULL;
    ui_CompassPageImg = NULL;
    ui_CompassAngleBtn = NULL;
    ui_AngleIconLabel = NULL;
    ui_AngelColonIcon = NULL;
    ui_AngelNum = NULL;
    ui_CompassAltitudeBtn = NULL;
    ui_AltitudeIconLabel = NULL;
    ui_AltitudeColonIcon = NULL;
    ui_ui_AltitudeNum = NULL;
    compass_scale = NULL;
}

static void compass_page_init()
{
	ui_CompassPage_screen_init();
}

static void compass_page_deinit()
{
	 ui_CompassPage_screen_destroy();
}

static void compass_page_resume() 
{
    if(ui_CompassPageTimer == NULL)     
        ui_CompassPageTimer = lv_timer_create(compass_page_timer_cb, 500, NULL);     
   
	 //立马触发一次测量
	 sensor_msg_t msg = MSG_COMPASS_MEASURE;
	 osMessageQueuePut(SensorMsgQueue, &msg, NULL, 0); 
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void compass_page_pause()
{
    if (ui_CompassPageTimer) {
        lv_timer_del(ui_CompassPageTimer); 
        ui_CompassPageTimer = NULL;
    }
	// 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}


page_t page_compass = {
	.page_obj = &ui_CompassPage,
	.init = compass_page_init,
	.deinit = compass_page_deinit,
	.resume = compass_page_resume,
	.pause = compass_page_pause,
};