// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: CalendarPage

#include "ui_CalendarPage.h"

lv_obj_t * ui_CalendarPage = NULL;
lv_obj_t * ui_Calendar = NULL;
// event funtions

// static void calendar_page_event_cb(lv_event_t* e)
// {
// 	lv_event_code_t event_code = lv_event_get_code(e);
// 	lv_obj_t * target = lv_event_get_target(e);
	
// 	if(event_code == LV_EVENT_GESTURE)
// 	{
// 			lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
// 			if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
//       {
// 				 page_back();
//       }
// 	}
// }

// build funtions

void ui_CalendarPage_screen_init(void)
{
    ui_CalendarPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CalendarPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar = lv_calendar_create(ui_CalendarPage);
    lv_calendar_set_today_date(ui_Calendar, 2025, 8, 15);
    lv_calendar_set_showed_date(ui_Calendar, 2025, 8);
    lv_obj_t * ui_Calendar_header = lv_calendar_header_arrow_create(ui_Calendar);
    lv_obj_set_width(ui_Calendar, 240);
    lv_obj_set_height(ui_Calendar, 280);
    lv_obj_set_align(ui_Calendar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
		
	//lv_obj_add_event_cb(ui_CalendarPage,calendar_page_event_cb,LV_EVENT_GESTURE,NULL); // 回调函数
}

void ui_CalendarPage_screen_destroy(void)
{
    if(ui_CalendarPage) lv_obj_del(ui_CalendarPage);

    // NULL screen variables
    ui_CalendarPage = NULL;
    ui_Calendar = NULL;

}

static void calendar_page_init()
{
	ui_CalendarPage_screen_init();
}

static void calendar_page_deinit()
{
	ui_CalendarPage_screen_destroy();
}

static void calendar_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void calendar_page_pause()
{
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_calendar = 
{
	.page_obj = &ui_CalendarPage,
	.init = calendar_page_init,
	.deinit = calendar_page_deinit,
	.resume = calendar_page_resume,
	.pause = calendar_page_pause,
};


