  // This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: testpage

#include "ui_HomePage.h"
#include "ui_MenuPage.h"
#include "ui_SettingMenuPage.h"
#include "hw_interface.h"
#include "page_manager.h"
#include "SEGGER_RTT.h"

lv_obj_t * ui_HomePage = NULL;
lv_obj_t * ui_BatLabel = NULL;
lv_obj_t * ui_StepNumLabel = NULL;
lv_obj_t * ui_HRNumLabel = NULL;
lv_obj_t * ui_BatNumLabel = NULL;
lv_obj_t * ui_TimeHourLabel = NULL;
lv_obj_t * ui_TimeMinuteLabel = NULL;
lv_obj_t * ui_HRBPMArc = NULL;
lv_obj_t * ui_HRBPMIconLabel = NULL;
lv_obj_t * ui_StepArc = NULL;
lv_obj_t * ui_StepIconLabel = NULL;
lv_obj_t * ui_BatArc = NULL;
lv_obj_t * ui_BatIconLabel = NULL;
lv_obj_t * ui_DateButton = NULL;
lv_obj_t * ui_DayLabel = NULL;
lv_obj_t * ui_DateLabel = NULL;
lv_obj_t * ui_StepsLabel = NULL;
lv_obj_t * ui_HRBPMLabel = NULL;
lv_obj_t * ui_DropDownPanel = NULL;
lv_obj_t * ui_UpBGPanel = NULL;
lv_obj_t * ui_NFCButton = NULL;
lv_obj_t * ui_NFCLabel = NULL;
lv_obj_t * ui_BLEButton = NULL;
lv_obj_t * ui_BLELabel = NULL;
lv_obj_t * ui_PowerButton = NULL;
lv_obj_t * ui_PowerLabel = NULL;
lv_obj_t * ui_SetButton = NULL;
lv_obj_t * ui_SetLabel = NULL;
lv_obj_t * ui_LightSlider = NULL;
lv_obj_t * ui_LightLabel = NULL;
lv_obj_t * ui_DownBGPanel = NULL;

lv_timer_t * ui_HomePageTimer = NULL; //首页定时器回调函数

const char* ui_weekdays[7] = {"星期一","星期二","星期三","星期四","星期五.","星期六","星期日"};

uint8_t ui_TimeHourValue = 11;
uint8_t ui_TimeMinuteValue = 59;
uint8_t ui_DateMonthValue = 11;  
uint8_t ui_DateDayValue = 8;
uint8_t ui_DataWeekdayValue = 2;

uint8_t ui_BatArcValue = 80;
uint16_t ui_StepNumValue = 0;
uint8_t ui_LightSliderValue = 50;

uint8_t ui_HomePageBleEnFlag = 0; // 蓝牙按钮事件使能标志，0表示未使能，1表示已使能
uint8_t ui_HomePageNfcEnFlag = 0; // NFC按钮事件使能标志，0表示未使能，1表示已使能


// event functions
static void home_page_event_cb(lv_event_t * e)
{
	
	lv_event_code_t event_code = lv_event_get_code(e); //获取触发事件类型
    lv_obj_t * event_target = lv_event_get_target(e);  //获取触发事件的对象(控件)

    if(event_code == LV_EVENT_GESTURE)
    {
		lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
		if(dir == LV_DIR_RIGHT) // 从输入检测手势左滑
        {
			 page_load(&page_menu);
        }
	}
	
}

static void home_page_timer_cb(lv_timer_t * timer)
{
    uint8_t value_buffer[10];
	if(get_top_page()->page_obj == &ui_HomePage) // 仅在HomePage位于页面栈顶时更新显示
    {

        hw_date_time_t date_time;
        hw_interface.hw_rtc_interface->get_time_date(&date_time); // 从RTC获取当前时间日期

        /* 仅在日期或星期发生变化时更新显示，避免不必要的刷新 */
        if(ui_DateMonthValue != date_time.month || ui_DateDayValue != date_time.date)
        {
            ui_DateMonthValue = date_time.month;  
            ui_DateDayValue = date_time.date;
            ui_DataWeekdayValue = date_time.weekday;
            sprintf((char*)value_buffer, "%d/%d",ui_DateMonthValue,ui_DateDayValue);
            lv_label_set_text(ui_DateLabel, (const char*)value_buffer); // 更新日期显示
            lv_label_set_text(ui_DayLabel, ui_weekdays[ui_DataWeekdayValue - 1]); // 更新星期显示
        }

        /* 仅在时间发生变化时更新显示，避免不必要的刷新 */
        if(ui_TimeHourValue != date_time.hours || ui_TimeMinuteValue != date_time.minutes) // 
        {
            ui_TimeHourValue = date_time.hours;
            ui_TimeMinuteValue = date_time.minutes;
            sprintf((char*)value_buffer, "%02d",ui_TimeHourValue);
            lv_label_set_text(ui_TimeHourLabel, (const char*)value_buffer); // 更新小时显示
            sprintf((char*)value_buffer, "%02d",ui_TimeMinuteValue);
            lv_label_set_text(ui_TimeMinuteLabel, (const char*)value_buffer); // 更新分钟显示
        }

        if(ui_BatArcValue != hw_interface.hw_power_interface->remain_power)
        {
            ui_BatArcValue = hw_interface.hw_power_interface->remain_power;
            lv_arc_set_value(ui_BatArc, ui_BatArcValue); // 更新电量圆弧显示
            sprintf((char*)value_buffer, "%d%%",ui_BatArcValue);
            lv_label_set_text(ui_BatNumLabel, (const char*)value_buffer); // 更新电量百分比显示
        }

        if (ui_StepNumValue != hw_interface.hw_mpu6050_interface->steps)
        {
            ui_StepNumValue = hw_interface.hw_mpu6050_interface->steps;
            sprintf(value_buffer, "%d",ui_StepNumValue);
            lv_label_set_text(ui_StepNumLabel, value_buffer); // 更新步数显示
        }
        
    }
}

static void home_page_nfc_button_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e); //获取触发事件类型
    lv_obj_t * event_target = lv_event_get_target(e);  //获取触发事件的对象(控件)

    if(event_code == LV_EVENT_VALUE_CHANGED)
    {
        if(lv_obj_has_state(event_target, LV_STATE_CHECKED)) 
        {
            ui_HomePageNfcEnFlag = 1; 
        }
        else 
        {
            ui_HomePageNfcEnFlag = 0; 
        }

    }
}

static void home_page_ble_button_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e); //获取触发事件类型
    lv_obj_t * event_target = lv_event_get_target(e);  //获取触发事件的对象(控件)

    if(event_code == LV_EVENT_VALUE_CHANGED)
    {
        if(lv_obj_has_state(event_target, LV_STATE_CHECKED)) // 如果蓝牙按钮被选中
        {
            hw_interface.hw_ble_interface->enable(); 
            ui_HomePageBleEnFlag = 1; 
        }
        else // 如果蓝牙按钮被取消
        {
            hw_interface.hw_ble_interface->disable(); 
            ui_HomePageBleEnFlag = 0; 
        }

    }
}

static void home_page_power_button_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e); //获取触发事件类型
    lv_obj_t * event_target = lv_event_get_target(e);  //获取触发事件的对象(控件)

    if(event_code == LV_EVENT_CLICKED)
    {
        //page_load(&page_power);
    }
}

static void hoome_page_set_button_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e); //获取触发事件类型
    lv_obj_t * event_target = lv_event_get_target(e);  //获取触发事件的对象(控件)

    if(event_code == LV_EVENT_CLICKED)
    {
       page_load(&page_setting_menu);
    }
}

static void home_page_light_slider_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e); //获取触发事件类型
    lv_obj_t * event_target = lv_event_get_target(e);  //获取触发事件的对象(控件)

    if(event_code == LV_EVENT_VALUE_CHANGED)
    {
        ui_LightSliderValue = lv_slider_get_value(event_target);
        hw_interface.hw_lcd_interface->set_light(ui_LightSliderValue);
    }
}

// build funtions

void ui_HomePage_screen_init(void)
{
    uint8_t value_buffer[10];

   ui_HomePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatLabel = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_BatLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatLabel, -26);
    lv_obj_set_y(ui_BatLabel, -99);
    lv_obj_set_align(ui_BatLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatLabel, "Battery");
    lv_obj_set_style_text_color(ui_BatLabel, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatLabel, &ui_font_OpenSasnsItalic15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepNumLabel = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_StepNumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StepNumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StepNumLabel, -28);
    lv_obj_set_y(ui_StepNumLabel, -10);
    lv_obj_set_align(ui_StepNumLabel, LV_ALIGN_CENTER);
    sprintf(value_buffer, "%d",ui_StepNumValue);
    lv_label_set_text(ui_StepNumLabel,value_buffer); // 初始步数显示
    lv_obj_set_style_text_font(ui_StepNumLabel, &ui_font_OpenSasnsItalic15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HRNumLabel = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_HRNumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HRNumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HRNumLabel, -30);
    lv_obj_set_y(ui_HRNumLabel, 59);
    lv_obj_set_align(ui_HRNumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HRNumLabel, "87");
    lv_obj_set_style_text_font(ui_HRNumLabel, &ui_font_OpenSasnsItalic15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatNumLabel = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_BatNumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatNumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatNumLabel, -26);
    lv_obj_set_y(ui_BatNumLabel, -81);
    lv_obj_set_align(ui_BatNumLabel, LV_ALIGN_CENTER);
    sprintf((char*)value_buffer, "%2d%%",ui_BatArcValue);
    lv_label_set_text(ui_BatNumLabel, (const char*)value_buffer); // 初始电量百分比显示
    lv_obj_set_style_text_font(ui_BatNumLabel, &ui_font_OpenSasnsItalic15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeHourLabel = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_TimeHourLabel, LV_SIZE_CONTENT);   //
    lv_obj_set_height(ui_TimeHourLabel, LV_SIZE_CONTENT);    //
    lv_obj_set_x(ui_TimeHourLabel, 59);
    lv_obj_set_y(ui_TimeHourLabel, -73);
    lv_obj_set_align(ui_TimeHourLabel, LV_ALIGN_CENTER);
    sprintf((char*)value_buffer, "%02d",ui_TimeHourValue);
    lv_label_set_text(ui_TimeHourLabel, (const char*)value_buffer); // 初始小时显示
    lv_obj_set_style_text_font(ui_TimeHourLabel, &ui_font_OpenSasnsItalic100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_TimeHourLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_TimeHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TimeHourLabel, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeMinuteLabel = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_TimeMinuteLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeMinuteLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeMinuteLabel, 57);
    lv_obj_set_y(ui_TimeMinuteLabel, 33);
    lv_obj_set_align(ui_TimeMinuteLabel, LV_ALIGN_CENTER);
    sprintf((char*)value_buffer, "%02d",ui_TimeMinuteValue);
    lv_label_set_text(ui_TimeMinuteLabel, (const char*)value_buffer); // 初始分钟显示
    lv_obj_set_style_text_color(ui_TimeMinuteLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeMinuteLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeMinuteLabel, &ui_font_OpenSasnsItalic100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HRBPMArc = lv_arc_create(ui_HomePage);
    lv_obj_set_width(ui_HRBPMArc, 55);
    lv_obj_set_height(ui_HRBPMArc, 55);
    lv_obj_set_x(ui_HRBPMArc, -80);
    lv_obj_set_y(ui_HRBPMArc, 50);
    lv_obj_set_align(ui_HRBPMArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HRBPMArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_HRBPMArc, 0, 200);
    lv_arc_set_value(ui_HRBPMArc, 66);
    lv_arc_set_bg_angles(ui_HRBPMArc, 90, 440);
    lv_obj_set_style_arc_width(ui_HRBPMArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_HRBPMArc, lv_color_hex(0xFC0740), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HRBPMArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_HRBPMArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HRBPMArc, lv_color_hex(0xFC0740), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HRBPMArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HRBPMArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HRBPMArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HRBPMArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HRBPMArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HRBPMIconLabel = lv_label_create(ui_HRBPMArc);
    lv_obj_set_width(ui_HRBPMIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HRBPMIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HRBPMIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HRBPMIconLabel, "");
    lv_obj_set_style_text_color(ui_HRBPMIconLabel, lv_color_hex(0xFC0740), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HRBPMIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HRBPMIconLabel, &ui_font_HPiconfont25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepArc = lv_arc_create(ui_HomePage);
    lv_obj_set_width(ui_StepArc, 55);
    lv_obj_set_height(ui_StepArc, 55);
    lv_obj_set_x(ui_StepArc, -80);
    lv_obj_set_y(ui_StepArc, -20);
    lv_obj_set_align(ui_StepArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_StepArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_StepArc, 75);
    lv_arc_set_bg_angles(ui_StepArc, 90, 440);
    lv_obj_set_style_arc_width(ui_StepArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_StepArc, lv_color_hex(0x66E4F9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_StepArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_StepArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_StepArc, lv_color_hex(0x66E4F9), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StepArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StepArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StepArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StepArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StepArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_StepIconLabel = lv_label_create(ui_StepArc);
    lv_obj_set_width(ui_StepIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StepIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StepIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StepIconLabel, "");
    lv_obj_set_style_text_color(ui_StepIconLabel, lv_color_hex(0x66E4F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StepIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StepIconLabel, &ui_font_HPiconfont25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatArc = lv_arc_create(ui_HomePage);
    lv_obj_set_width(ui_BatArc, 55);
    lv_obj_set_height(ui_BatArc, 55);
    lv_obj_set_x(ui_BatArc, -80);
    lv_obj_set_y(ui_BatArc, -90);
    lv_obj_set_align(ui_BatArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BatArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_BatArc, ui_BatArcValue); // 初始电量显示
    lv_arc_set_bg_angles(ui_BatArc, 90, 440);
    lv_obj_set_style_arc_width(ui_BatArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_BatArc, lv_color_hex(0x00FF7F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BatArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BatArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BatArc, lv_color_hex(0x00FF7F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatIconLabel = lv_label_create(ui_BatArc);
    lv_obj_set_width(ui_BatIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatIconLabel, "");
    lv_obj_set_style_text_color(ui_BatIconLabel, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatIconLabel, &ui_font_HPiconfont25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateButton = lv_button_create(ui_HomePage);
    lv_obj_set_width(ui_DateButton, 220);
    lv_obj_set_height(ui_DateButton, 35);
    lv_obj_set_x(ui_DateButton, 1);
    lv_obj_set_y(ui_DateButton, 110);
    lv_obj_set_align(ui_DateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DateButton, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DateButton, lv_color_hex(0x222422), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DateButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DayLabel = lv_label_create(ui_DateButton);
    lv_obj_set_width(ui_DayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DayLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DayLabel, ui_weekdays[ui_DataWeekdayValue - 1]);
    lv_obj_set_style_text_font(ui_DayLabel, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_DateButton);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DayLabel, LV_ALIGN_RIGHT_MID);
    sprintf((char*)value_buffer, "%d/%d",ui_DateMonthValue,ui_DateDayValue);
    lv_label_set_text(ui_DateLabel,(const char*)value_buffer);
    lv_obj_set_style_text_font(ui_DateLabel, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepsLabel = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_StepsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StepsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StepsLabel, -27);
    lv_obj_set_y(ui_StepsLabel, -28);
    lv_obj_set_align(ui_StepsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StepsLabel, "STEPS");
    lv_obj_set_style_text_color(ui_StepsLabel, lv_color_hex(0x66E4F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StepsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StepsLabel, &ui_font_OpenSasnsItalic15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HRBPMLabel = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_HRBPMLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HRBPMLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HRBPMLabel, -30);
    lv_obj_set_y(ui_HRBPMLabel, 42);
    lv_obj_set_align(ui_HRBPMLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HRBPMLabel, "BPM");
    lv_obj_set_style_text_color(ui_HRBPMLabel, lv_color_hex(0xFC0740), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HRBPMLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HRBPMLabel, &ui_font_OpenSasnsItalic15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropDownPanel = lv_obj_create(ui_HomePage);
    lv_obj_set_width(ui_DropDownPanel, 240);
    lv_obj_set_height(ui_DropDownPanel, 420);
    lv_obj_set_x(ui_DropDownPanel, 0);
    lv_obj_set_y(ui_DropDownPanel, -10); 
    lv_obj_set_align(ui_DropDownPanel, LV_ALIGN_TOP_MID);
    lv_obj_scroll_by(ui_DropDownPanel,0,-130,LV_ANIM_OFF); // 将面板中的所有内容隐藏在屏幕顶部
    //lv_obj_remove_flag(ui_DropDownPanel,LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_remove_flag(ui_DropDownPanel, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_CHAIN); // 允许点击但禁止弹性和链式滚动
    lv_obj_set_scroll_dir(ui_DropDownPanel, LV_DIR_VER); // 仅允许垂直滚动
	lv_obj_set_style_bg_color(ui_DropDownPanel, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropDownPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DropDownPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DropDownPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_bg_color(ui_DropDownPanel, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropDownPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropDownPanel, 0, LV_PART_SCROLLBAR | LV_STATE_SCROLLED); // 将滚动条背景完全透明，避免显示滚动条

    ui_UpBGPanel = lv_obj_create(ui_DropDownPanel);
    lv_obj_set_width(ui_UpBGPanel, 240);
    lv_obj_set_height(ui_UpBGPanel, 130);
    lv_obj_set_x(ui_UpBGPanel, 0);
    lv_obj_set_y(ui_UpBGPanel, -10);
    lv_obj_set_align(ui_UpBGPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_UpBGPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UpBGPanel, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UpBGPanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NFCButton = lv_button_create(ui_DropDownPanel);
    lv_obj_set_width(ui_NFCButton, 50);
    lv_obj_set_height(ui_NFCButton, 50);
    lv_obj_set_x(ui_NFCButton, 0);
    lv_obj_set_y(ui_NFCButton, 5); 
    lv_obj_add_flag(ui_NFCButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_NFCButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NFCButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NFCButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //将选中状态的背景颜色从红色设置为蓝色，并保持不透明
    lv_obj_set_style_bg_color(ui_NFCButton, lv_color_hex(0x3264C8), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_NFCButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    if(ui_HomePageNfcEnFlag)
    {
        lv_obj_add_state(ui_NFCButton, LV_STATE_CHECKED); // 根据标志位设置初始状态
    }


    ui_NFCLabel = lv_label_create(ui_NFCButton);
    lv_obj_set_width(ui_NFCLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NFCLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NFCLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NFCLabel, "");
    lv_obj_set_style_text_color(ui_NFCLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NFCLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NFCLabel, &ui_font_iconfont34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLEButton = lv_button_create(ui_DropDownPanel);
    lv_obj_set_width(ui_BLEButton, 50);
    lv_obj_set_height(ui_BLEButton, 50);
    lv_obj_set_x(ui_BLEButton, 0);
    lv_obj_set_y(ui_BLEButton, 65);
    lv_obj_add_flag(ui_BLEButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BLEButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLEButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLEButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //将选中状态的背景颜色从红色设置为蓝色，并保持不透明
    lv_obj_set_style_bg_color(ui_BLEButton, lv_color_hex(0x3264C8), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BLEButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    if(ui_HomePageBleEnFlag)
    {
        lv_obj_add_state(ui_BLEButton, LV_STATE_CHECKED); // 根据标志位设置初始状态
    }

    ui_BLELabel = lv_label_create(ui_BLEButton);
    lv_obj_set_width(ui_BLELabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLELabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BLELabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLELabel, "");
    lv_obj_set_style_text_color(ui_BLELabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLELabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLELabel, &ui_font_iconfont34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerButton = lv_button_create(ui_DropDownPanel);
    lv_obj_set_width(ui_PowerButton, 50);
    lv_obj_set_height(ui_PowerButton, 50);
    lv_obj_set_x(ui_PowerButton, 0);
    lv_obj_set_y(ui_PowerButton, 5);
    lv_obj_set_align(ui_PowerButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PowerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PowerButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PowerButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerLabel = lv_label_create(ui_PowerButton);
    lv_obj_set_width(ui_PowerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerLabel, "");
    lv_obj_set_style_text_color(ui_PowerLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PowerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PowerLabel, &ui_font_iconfont34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetButton = lv_button_create(ui_DropDownPanel);
    lv_obj_set_width(ui_SetButton, 50);
    lv_obj_set_height(ui_SetButton, 50);
    lv_obj_set_x(ui_SetButton, 0);
    lv_obj_set_y(ui_SetButton, 65);
    lv_obj_set_align(ui_SetButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetLabel = lv_label_create(ui_SetButton);
    lv_obj_set_width(ui_SetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetLabel, "");
    lv_obj_set_style_text_color(ui_SetLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetLabel, &ui_font_iconfont34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightSlider = lv_slider_create(ui_DropDownPanel);
    lv_slider_set_value(ui_LightSlider, ui_LightSliderValue, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LightSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LightSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LightSlider, 50);
    lv_obj_set_height(ui_LightSlider, 110);
    lv_obj_set_x(ui_LightSlider, 0);
    lv_obj_set_y(ui_LightSlider, 5);
    lv_obj_set_align(ui_LightSlider, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_radius(ui_LightSlider, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightSlider, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_LightSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightSlider, lv_color_hex(0x3264C8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LightSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_LightSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_LightSlider,
                                                                                                  lv_obj_get_style_pad_right(ui_LightSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LightLabel = lv_label_create(ui_LightSlider);
    lv_obj_set_width(ui_LightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightLabel, 0);
    lv_obj_set_y(ui_LightLabel, 30);
    lv_obj_set_align(ui_LightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightLabel, "");
    lv_obj_set_style_text_color(ui_LightLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightLabel, &ui_font_iconfont34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DownBGPanel = lv_obj_create(ui_DropDownPanel);
    lv_obj_set_width(ui_DownBGPanel, 240);
    lv_obj_set_height(ui_DownBGPanel, 130);
    lv_obj_set_x(ui_DownBGPanel, 0);
    lv_obj_set_y(ui_DownBGPanel, 420);
    lv_obj_set_align(ui_DownBGPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_DownBGPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DownBGPanel, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DownBGPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DownBGPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DownBGPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	lv_obj_add_event_cb(ui_HomePage, home_page_event_cb, LV_EVENT_GESTURE, NULL); // home页面事件回调函数
    lv_obj_add_event_cb(ui_NFCButton, home_page_nfc_button_cb, LV_EVENT_ALL, NULL); // NFC按钮事件回调函数
    lv_obj_add_event_cb(ui_BLEButton, home_page_ble_button_cb, LV_EVENT_ALL, NULL); // 蓝牙按钮事件回调函数
    lv_obj_add_event_cb(ui_PowerButton, home_page_power_button_cb, LV_EVENT_ALL, NULL); // 电源按钮事件回调函数
    lv_obj_add_event_cb(ui_SetButton, hoome_page_set_button_cb, LV_EVENT_ALL, NULL); // 设置按钮事件回调函数
	lv_obj_add_event_cb(ui_LightSlider, home_page_light_slider_cb, LV_EVENT_ALL, NULL); // 亮度滑块事件回调函数

    ui_HomePageTimer = lv_timer_create(home_page_timer_cb,500,NULL);
}

void ui_HomePage_screen_destroy(void)
{
    if(ui_HomePage) lv_obj_del(ui_HomePage);

    // NULL screen variables
    ui_HomePage = NULL;
    ui_BatLabel = NULL;
    ui_StepNumLabel = NULL;
    ui_HRNumLabel = NULL;
    ui_BatNumLabel = NULL;
    ui_TimeHourLabel = NULL;
    ui_TimeMinuteLabel = NULL;
    ui_HRBPMArc = NULL;
    ui_HRBPMIconLabel = NULL;
    ui_StepArc = NULL;
    ui_StepIconLabel = NULL;
    ui_BatArc = NULL;
    ui_BatIconLabel = NULL;
    ui_DateButton = NULL;
    ui_DayLabel = NULL;
    ui_DateLabel = NULL;
    ui_StepsLabel = NULL;
    ui_HRBPMLabel = NULL;
    ui_DropDownPanel = NULL;
    ui_UpBGPanel = NULL;
    ui_NFCButton = NULL;
    ui_NFCLabel = NULL;
    ui_BLEButton = NULL;
    ui_BLELabel = NULL;
    ui_PowerButton = NULL;
    ui_PowerLabel = NULL;
    ui_SetButton = NULL;
    ui_SetLabel = NULL;
    ui_LightSlider = NULL;
    ui_LightLabel = NULL;
    ui_DownBGPanel = NULL;
		
}


static void home_page_init()
{
	ui_HomePage_screen_init();
	
}

static void home_page_deinit()
{
	ui_HomePage_screen_destroy();
}

static void home_page_resume() 
{
    // if(ui_HomePageTimer == NULL) {
    //     ui_HomePageTimer = lv_timer_create(home_page_timer_cb, 500, NULL); // 创建定时器，500ms回调一次
    // }
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void home_page_pause()
{
    // if(ui_HomePageTimer) {
    //     lv_timer_del(ui_HomePageTimer); // 删除定时器
    //     ui_HomePageTimer = NULL;
    // }
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}



page_t page_home = 
{
	.page_obj = &ui_HomePage,
	.init = home_page_init,
	.deinit = home_page_deinit,
	.resume = home_page_resume,
	.pause = home_page_pause,
};
