// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#include "ui_SOffTimeSetPage.h"

lv_obj_t * ui_SOffTimeSetPage = NULL;
lv_obj_t * ui_SOffTimeNumRoller = NULL;
lv_obj_t * ui_SOffSecondLabel = NULL;
lv_obj_t * ui_SOffTimeIconLabel = NULL;
lv_obj_t * ui_SOffTimeSetOKButton = NULL;
lv_obj_t * ui_SOffTimeSetOKIconLabel = NULL;
// event funtions

static void s_off_set_page_event_cb(lv_event_t* e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_GESTURE)
    {
	    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
		  if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
      {
				page_back();
      }
	}
}

static void set_ok_button_event_cb(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e); // 获取事件
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_CLICKED)
    {

        page_back();
    }

}

// build funtions

void ui_SOffTimeSetPage_screen_init(void)
{
    ui_SOffTimeSetPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SOffTimeSetPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SOffTimeNumRoller = lv_roller_create(ui_SOffTimeSetPage);
    lv_roller_set_options(ui_SOffTimeNumRoller, "10\n15\n20\n30\n45\n60", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_SOffTimeNumRoller, 150);
    lv_obj_set_width(ui_SOffTimeNumRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SOffTimeNumRoller, -1);
    lv_obj_set_y(ui_SOffTimeNumRoller, -22);
    lv_obj_set_align(ui_SOffTimeNumRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_SOffTimeNumRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SOffTimeNumRoller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SOffTimeNumRoller, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SOffTimeNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOffTimeNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SOffTimeNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SOffTimeNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SOffTimeNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SOffTimeNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SOffTimeNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SOffTimeNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SOffTimeNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SOffTimeNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOffTimeNumRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SOffTimeNumRoller, lv_color_hex(0x0064FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SOffTimeNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SOffTimeNumRoller, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SOffTimeNumRoller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_SOffSecondLabel = lv_label_create(ui_SOffTimeSetPage);
    lv_obj_set_width(ui_SOffSecondLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOffSecondLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SOffSecondLabel, 65);
    lv_obj_set_y(ui_SOffSecondLabel, -22);
    lv_obj_set_align(ui_SOffSecondLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOffSecondLabel, "秒");
    lv_obj_set_style_text_font(ui_SOffSecondLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOffTimeIconLabel = lv_label_create(ui_SOffTimeSetPage);
    lv_obj_set_width(ui_SOffTimeIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOffTimeIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SOffTimeIconLabel, -1);
    lv_obj_set_y(ui_SOffTimeIconLabel, -109);
    lv_obj_set_align(ui_SOffTimeIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOffTimeIconLabel, "");
    lv_obj_set_style_text_color(ui_SOffTimeIconLabel, lv_color_hex(0x2619E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SOffTimeIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SOffTimeIconLabel, &ui_font_LTSiconfont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOffTimeSetOKButton = lv_button_create(ui_SOffTimeSetPage);
    lv_obj_set_width(ui_SOffTimeSetOKButton, 240);
    lv_obj_set_height(ui_SOffTimeSetOKButton, 50);
    lv_obj_set_align(ui_SOffTimeSetOKButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SOffTimeSetOKButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SOffTimeSetOKButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SOffTimeSetOKButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SOffTimeSetOKButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOffTimeSetOKButton, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SOffTimeSetOKButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SOffTimeSetOKButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SOffTimeSetOKIconLabel = lv_label_create(ui_SOffTimeSetOKButton);
    lv_obj_set_width(ui_SOffTimeSetOKIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOffTimeSetOKIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SOffTimeSetOKIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOffTimeSetOKIconLabel, "");
    lv_obj_set_style_text_font(ui_SOffTimeSetOKIconLabel, &ui_font_LTSiconfont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SOffTimeSetOKButton,set_ok_button_event_cb,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_SOffTimeSetPage,s_off_set_page_event_cb,LV_EVENT_GESTURE,NULL);
}

void ui_SOffTimeSetPage_screen_destroy(void)
{
    if(ui_SOffTimeSetPage) lv_obj_del(ui_SOffTimeSetPage);

    // NULL screen variables
    ui_SOffTimeSetPage = NULL;
    ui_SOffTimeNumRoller = NULL;
    ui_SOffSecondLabel = NULL;
    ui_SOffTimeIconLabel = NULL;
    ui_SOffTimeSetOKButton = NULL;
    ui_SOffTimeSetOKIconLabel = NULL;

}


static void screen_off_time_set_page_init()
{
	ui_SOffTimeSetPage_screen_init();
}

static void screen_off_time_set_page_deinit()
{
	ui_SOffTimeSetPage_screen_destroy();
}

static void screen_off_time_set_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void screen_off_time_set_page_pause()
{
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_screen_off_time_set = 
{
	.page_obj = &ui_SOffTimeSetPage,
	.init = screen_off_time_set_page_init,
	.deinit = screen_off_time_set_page_deinit,
	.resume = screen_off_time_set_page_resume,
	.pause = screen_off_time_set_page_pause,
};