// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SpO2MeasurePage

#include "ui_SpO2MeasurePage.h"

lv_obj_t * ui_SpO2MeasurePage = NULL;
lv_obj_t * ui_SpO2IconLabel = NULL;
lv_obj_t * ui_SpO2NumLabel = NULL;
lv_obj_t * ui_PercentLabel = NULL;
lv_obj_t * ui_SpO2MeasureLabel = NULL;
// event funtions

// static void SpO2_page_event_cb(lv_event_t* e)
// {
// 	lv_event_code_t event_code = lv_event_get_code(e);
// 	lv_obj_t * target = lv_event_get_target(e);
	
// 	if(event_code == LV_EVENT_GESTURE)
// 	{
// 			lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
// 			if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
//       {
// 				 page_back();
//       }
// 	}
// }

// build funtions

void ui_SpO2MeasurePage_screen_init(void)
{
    ui_SpO2MeasurePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SpO2MeasurePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpO2IconLabel = lv_label_create(ui_SpO2MeasurePage);
    lv_obj_set_width(ui_SpO2IconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpO2IconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpO2IconLabel, 0);
    lv_obj_set_y(ui_SpO2IconLabel, -84);
    lv_obj_set_align(ui_SpO2IconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpO2IconLabel, "");
    lv_obj_set_style_text_color(ui_SpO2IconLabel, lv_color_hex(0x0081FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpO2IconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpO2IconLabel, &ui_font_O2MPiconfont50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpO2NumLabel = lv_label_create(ui_SpO2MeasurePage);
    lv_obj_set_width(ui_SpO2NumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpO2NumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpO2NumLabel, -4);
    lv_obj_set_y(ui_SpO2NumLabel, 0);
    lv_obj_set_align(ui_SpO2NumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpO2NumLabel, "99");
    lv_obj_set_style_text_font(ui_SpO2NumLabel, &ui_font_CuYuan60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PercentLabel = lv_label_create(ui_SpO2MeasurePage);
    lv_obj_set_width(ui_PercentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentLabel, 84);
    lv_obj_set_y(ui_PercentLabel, 12);
    lv_obj_set_align(ui_PercentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PercentLabel, "%");
    lv_obj_set_style_text_font(ui_PercentLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpO2MeasureLabel = lv_label_create(ui_SpO2MeasurePage);
    lv_obj_set_width(ui_SpO2MeasureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpO2MeasureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpO2MeasureLabel, 4);
    lv_obj_set_y(ui_SpO2MeasureLabel, 79);
    lv_obj_set_align(ui_SpO2MeasureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpO2MeasureLabel, "正在测量...");
    lv_obj_set_style_text_color(ui_SpO2MeasureLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpO2MeasureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpO2MeasureLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);
		
		
	//lv_obj_add_event_cb(ui_SpO2MeasurePage,SpO2_page_event_cb, LV_EVENT_GESTURE, NULL); // 回调函数
}

void ui_SpO2MeasurePage_screen_destroy(void)
{
    if(ui_SpO2MeasurePage) lv_obj_del(ui_SpO2MeasurePage);

    // NULL screen variables
    ui_SpO2MeasurePage = NULL;
    ui_SpO2IconLabel = NULL;
    ui_SpO2NumLabel = NULL;
    ui_PercentLabel = NULL;
    ui_SpO2MeasureLabel = NULL;

}

static void SpO2_page_init()
{
	ui_SpO2MeasurePage_screen_init();
}

static void SpO2_page_deinit()
{
	ui_SpO2MeasurePage_screen_destroy();
}

static void SpO2_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void SpO2_page_pause()
{
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_SpO2 = 
{
	.page_obj = &ui_SpO2MeasurePage,
	.init = SpO2_page_init,
	.deinit = SpO2_page_deinit,
	.resume = SpO2_page_resume,
	.pause = SpO2_page_pause,
};