// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SettingPage

#include "ui_SettingMenuPage.h"
#include "ui_DateTimeMenuPage.h"
#include "ui_SOffTimeSetPage.h"
#include "ui_LTSetPage.h"

lv_obj_t * ui_SettingMenuPage = NULL;
lv_obj_t * ui_MenuLightTimePanel = NULL;
lv_obj_t * ui_LightTimeButton = NULL;
lv_obj_t * ui_LightTimeIconLabel = NULL;
lv_obj_t * ui_LightTimeLabel = NULL;
lv_obj_t * ui_MenuScrrenOffPanel = NULL;
lv_obj_t * ui_ScrrenOffButton = NULL;
lv_obj_t * ui_ScrrenOffIconLabel = NULL;
lv_obj_t * ui_ScrrenOffLabel = NULL;
lv_obj_t * ui_MenuDataTimePanel = NULL;
lv_obj_t * ui_DataTimeButton = NULL;
lv_obj_t * ui_DataTimeIconLabel = NULL;
lv_obj_t * ui_DataTimeLabel = NULL;
lv_obj_t * ui_MenuWristUpPanel = NULL;
lv_obj_t * ui_WristUpButton = NULL;
lv_obj_t * ui_WristUpIconLabel = NULL;
lv_obj_t * ui_WristUpLabel = NULL;
lv_obj_t * ui_WristUpSwitch = NULL;
lv_obj_t * ui_MenuPwdSetPanel = NULL;
lv_obj_t * ui_PwdSetButton = NULL;
lv_obj_t * ui_PwdSetIconLabel = NULL;
lv_obj_t * ui_PwdSetLabel = NULL;
// event funtions

static void setting_page_event_cb(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_GESTURE)
    {
	    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
		if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
        {
			page_back();
        }
	}
}


static void light_time_panel_event_cb(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e); // 获取事件
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_CLICKED)
	{
		page_load(&page_light_time_set_page);
	}
}

static void screen_off_panel_event_cb(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e); // 获取事件
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_CLICKED)
    {
        page_load(&page_screen_off_time_set);
    }
}

static void date_time_panel_event_cb(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e); // 获取事件
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_CLICKED)
    {
        page_load(&page_date_time_menu);
    }
}

// static void pwd_set_panel_event_cb(lv_event_t* e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e); // 获取事件
//     lv_obj_t * target = lv_event_get_target(e);
    
//     if(event_code == LV_EVENT_CLICKED)
//     {
//         //page_load(&page_pwd_set_menu);
//     }
// }

// build funtions

void ui_SettingMenuPage_screen_init(void)
{
    ui_SettingMenuPage = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_SettingMenuPage, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingMenuPage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_MenuLightTimePanel = lv_obj_create(ui_SettingMenuPage);
    lv_obj_set_width(ui_MenuLightTimePanel, 240);
    lv_obj_set_height(ui_MenuLightTimePanel, 63);
    lv_obj_set_align(ui_MenuLightTimePanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuLightTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuLightTimePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuLightTimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuLightTimePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuLightTimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuLightTimePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuLightTimePanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuLightTimePanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_border_color(ui_MenuLightTimePanel, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuLightTimePanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LightTimeButton = lv_button_create(ui_MenuLightTimePanel);
    lv_obj_set_width(ui_LightTimeButton, 40);
    lv_obj_set_height(ui_LightTimeButton, 40);
    lv_obj_set_align(ui_LightTimeButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_LightTimeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LightTimeButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LightTimeButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightTimeButton, lv_color_hex(0x0081FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightTimeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightTimeIconLabel = lv_label_create(ui_LightTimeButton);
    lv_obj_set_width(ui_LightTimeIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightTimeIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LightTimeIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightTimeIconLabel, "");
    lv_obj_set_style_text_font(ui_LightTimeIconLabel, &ui_font_SPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightTimeLabel = lv_label_create(ui_MenuLightTimePanel);
		lv_obj_set_x(ui_LightTimeLabel,-5);
    lv_obj_set_width(ui_LightTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LightTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightTimeLabel, "常亮时间");
    lv_obj_set_style_text_font(ui_LightTimeLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuScrrenOffPanel = lv_obj_create(ui_SettingMenuPage);
    lv_obj_set_width(ui_MenuScrrenOffPanel, 240);
    lv_obj_set_height(ui_MenuScrrenOffPanel, 63);
    lv_obj_set_x(ui_MenuScrrenOffPanel, -375);
    lv_obj_set_y(ui_MenuScrrenOffPanel, 124);
    lv_obj_set_align(ui_MenuScrrenOffPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuScrrenOffPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuScrrenOffPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuScrrenOffPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScrrenOffPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuScrrenOffPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuScrrenOffPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuScrrenOffPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuScrrenOffPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScrrenOffButton = lv_button_create(ui_MenuScrrenOffPanel);
    lv_obj_set_width(ui_ScrrenOffButton, 40);
    lv_obj_set_height(ui_ScrrenOffButton, 40);
    lv_obj_set_align(ui_ScrrenOffButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ScrrenOffButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScrrenOffButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScrrenOffButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScrrenOffButton, lv_color_hex(0xE68118), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrrenOffButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrrenOffIconLabel = lv_label_create(ui_ScrrenOffButton);
    lv_obj_set_width(ui_ScrrenOffIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrrenOffIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrrenOffIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrrenOffIconLabel, "");
    lv_obj_set_style_text_font(ui_ScrrenOffIconLabel, &ui_font_SPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrrenOffLabel = lv_label_create(ui_MenuScrrenOffPanel);
		lv_obj_set_x(ui_ScrrenOffLabel,-5);
    lv_obj_set_width(ui_ScrrenOffLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrrenOffLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrrenOffLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrrenOffLabel, "熄屏时间");
    lv_obj_set_style_text_font(ui_ScrrenOffLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuDataTimePanel = lv_obj_create(ui_SettingMenuPage);
    lv_obj_set_width(ui_MenuDataTimePanel, 240);
    lv_obj_set_height(ui_MenuDataTimePanel, 63);
    lv_obj_set_align(ui_MenuDataTimePanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuDataTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuDataTimePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuDataTimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuDataTimePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuDataTimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuDataTimePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuDataTimePanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuDataTimePanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_DataTimeButton = lv_button_create(ui_MenuDataTimePanel);
    lv_obj_set_width(ui_DataTimeButton, 40);
    lv_obj_set_height(ui_DataTimeButton, 40);
    lv_obj_set_align(ui_DataTimeButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DataTimeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DataTimeButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DataTimeButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DataTimeButton, lv_color_hex(0x0081FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DataTimeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DataTimeIconLabel = lv_label_create(ui_DataTimeButton);
    lv_obj_set_width(ui_DataTimeIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DataTimeIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DataTimeIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DataTimeIconLabel, "");
    lv_obj_set_style_text_color(ui_DataTimeIconLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DataTimeIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DataTimeIconLabel, &ui_font_SPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DataTimeLabel = lv_label_create(ui_MenuDataTimePanel);
		lv_obj_set_x(ui_DataTimeLabel,-5);
    lv_obj_set_width(ui_DataTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DataTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DataTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DataTimeLabel, "时间日期");
    lv_obj_set_style_text_font(ui_DataTimeLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuWristUpPanel = lv_obj_create(ui_SettingMenuPage);
    lv_obj_set_width(ui_MenuWristUpPanel, 240);
    lv_obj_set_height(ui_MenuWristUpPanel, 63);
    lv_obj_set_x(ui_MenuWristUpPanel, 19);
    lv_obj_set_y(ui_MenuWristUpPanel, -24);
    lv_obj_set_align(ui_MenuWristUpPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuWristUpPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuWristUpPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuWristUpPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuWristUpPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuWristUpPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuWristUpPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuWristUpPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuWristUpPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_WristUpButton = lv_button_create(ui_MenuWristUpPanel);
    lv_obj_set_width(ui_WristUpButton, 40);
    lv_obj_set_height(ui_WristUpButton, 40);
    lv_obj_set_align(ui_WristUpButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_WristUpButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WristUpButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WristUpButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WristUpButton, lv_color_hex(0x7B187B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WristUpButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WristUpIconLabel = lv_label_create(ui_WristUpButton);
    lv_obj_set_width(ui_WristUpIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WristUpIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WristUpIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WristUpIconLabel, "");
    lv_obj_set_style_text_font(ui_WristUpIconLabel, &ui_font_SPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WristUpLabel = lv_label_create(ui_MenuWristUpPanel);
		lv_obj_set_x(ui_WristUpLabel,-5);
    lv_obj_set_width(ui_WristUpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WristUpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WristUpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WristUpLabel, "抬腕亮屏");
    lv_obj_set_style_text_font(ui_WristUpLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WristUpSwitch = lv_switch_create(ui_MenuWristUpPanel);
    lv_obj_set_width(ui_WristUpSwitch, 60);
    lv_obj_set_height(ui_WristUpSwitch, 30);
    lv_obj_set_align(ui_WristUpSwitch, LV_ALIGN_RIGHT_MID);

    ui_MenuPwdSetPanel = lv_obj_create(ui_SettingMenuPage);
    lv_obj_set_width(ui_MenuPwdSetPanel, 240);
    lv_obj_set_height(ui_MenuPwdSetPanel, 63);
    lv_obj_set_align(ui_MenuPwdSetPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuPwdSetPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuPwdSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuPwdSetPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuPwdSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuPwdSetPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuPwdSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuPwdSetPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuPwdSetPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_PwdSetButton = lv_button_create(ui_MenuPwdSetPanel);
    lv_obj_set_width(ui_PwdSetButton, 40);
    lv_obj_set_height(ui_PwdSetButton, 40);
    lv_obj_set_align(ui_PwdSetButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PwdSetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PwdSetButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PwdSetButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PwdSetButton, lv_color_hex(0x009381), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PwdSetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PwdSetIconLabel = lv_label_create(ui_PwdSetButton);
    lv_obj_set_width(ui_PwdSetIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PwdSetIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PwdSetIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PwdSetIconLabel, "");
    lv_obj_set_style_text_font(ui_PwdSetIconLabel, &ui_font_SPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PwdSetLabel = lv_label_create(ui_MenuPwdSetPanel);
		lv_obj_set_x(ui_PwdSetLabel,-5);
    lv_obj_set_width(ui_PwdSetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PwdSetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PwdSetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PwdSetLabel, "密码设置");
    lv_obj_set_style_text_font(ui_PwdSetLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingMenuPage,setting_page_event_cb,LV_EVENT_GESTURE,NULL); // 滑动返回上个页面

    lv_obj_add_event_cb(ui_MenuLightTimePanel, light_time_panel_event_cb, LV_EVENT_CLICKED, NULL); // 常亮时间设置页面
    lv_obj_add_event_cb(ui_MenuScrrenOffPanel, screen_off_panel_event_cb, LV_EVENT_CLICKED, NULL); // 熄屏时间设置页面
    lv_obj_add_event_cb(ui_MenuDataTimePanel, date_time_panel_event_cb, LV_EVENT_CLICKED, NULL); // 时间日期设置页面
    //lv_obj_add_event_cb(ui_MenuPwdSetPanel, pwd_set_panel_event_cb, LV_EVENT_CLICKED, NULL);

}

void ui_SettingMenuPage_screen_destroy(void)
{
    if(ui_SettingMenuPage) lv_obj_del(ui_SettingMenuPage);

    // NULL screen variables
    ui_SettingMenuPage = NULL;
    ui_MenuLightTimePanel = NULL;
    ui_LightTimeButton = NULL;
    ui_LightTimeIconLabel = NULL;
    ui_LightTimeLabel = NULL;
    ui_MenuScrrenOffPanel = NULL;
    ui_ScrrenOffButton = NULL;
    ui_ScrrenOffIconLabel = NULL;
    ui_ScrrenOffLabel = NULL;
    ui_MenuDataTimePanel = NULL;
    ui_DataTimeButton = NULL;
    ui_DataTimeIconLabel = NULL;
    ui_DataTimeLabel = NULL;
    ui_MenuWristUpPanel = NULL;
    ui_WristUpButton = NULL;
    ui_WristUpIconLabel = NULL;
    ui_WristUpLabel = NULL;
    ui_WristUpSwitch = NULL;
    ui_MenuPwdSetPanel = NULL;
    ui_PwdSetButton = NULL;
    ui_PwdSetIconLabel = NULL;
    ui_PwdSetLabel = NULL;

}


static void setting_menu_page_init()
{
    ui_SettingMenuPage_screen_init();
}

static void setting_menu_page_deinit()
{
    ui_SettingMenuPage_screen_destroy();
}

static void setting_menu_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void setting_menu_page_pause()
{
      // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_setting_menu = 
{
    .page_obj = &ui_SettingMenuPage,
    .init = setting_menu_page_init,
    .deinit = setting_menu_page_deinit,
    .resume = setting_menu_page_resume,
    .pause = setting_menu_page_pause,
};