// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#include "ui_TimeSetPage.h"

lv_obj_t * ui_TimeSetPage = NULL;
lv_obj_t * ui_HourNumRoller = NULL;
lv_obj_t * ui_TimeSetOKButton = NULL;
lv_obj_t * ui_DateSetOKIconLabel1 = NULL;
lv_obj_t * ui_MinuteNumRoller = NULL;
lv_obj_t * ui_SecondNumRoller = NULL;
lv_obj_t * ui_HourMinColonLabel = NULL;
lv_obj_t * ui_MinSecColonLabel = NULL;
// event funtions

static void time_set_page_event_cb(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_GESTURE)
    {
	    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
		if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
        {
			page_back();
        }
	}
}


static void set_ok_button_event_cb(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e); // 获取事件
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_CLICKED)
    {

        page_back();
    }

}
// build funtions

void ui_TimeSetPage_screen_init(void)
{
    ui_TimeSetPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TimeSetPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HourNumRoller = lv_roller_create(ui_TimeSetPage);
    lv_roller_set_options(ui_HourNumRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_HourNumRoller, 130);
    lv_obj_set_width(ui_HourNumRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_HourNumRoller, -78);
    lv_obj_set_y(ui_HourNumRoller, -30);
    lv_obj_set_align(ui_HourNumRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_HourNumRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourNumRoller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourNumRoller, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HourNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HourNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HourNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HourNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_HourNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_HourNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_HourNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HourNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourNumRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_HourNumRoller, lv_color_hex(0x0064FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_HourNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_HourNumRoller, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_HourNumRoller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TimeSetOKButton = lv_button_create(ui_TimeSetPage);
    lv_obj_set_width(ui_TimeSetOKButton, 240);
    lv_obj_set_height(ui_TimeSetOKButton, 50);
    lv_obj_set_align(ui_TimeSetOKButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_TimeSetOKButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TimeSetOKButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimeSetOKButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeSetOKButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeSetOKButton, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeSetOKButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_TimeSetOKButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_DateSetOKIconLabel1 = lv_label_create(ui_TimeSetOKButton);
    lv_obj_set_width(ui_DateSetOKIconLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateSetOKIconLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DateSetOKIconLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateSetOKIconLabel1, "");
    lv_obj_set_style_text_font(ui_DateSetOKIconLabel1, &ui_font_LTSiconfont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinuteNumRoller = lv_roller_create(ui_TimeSetPage);
    lv_roller_set_options(ui_MinuteNumRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_MinuteNumRoller, 130);
    lv_obj_set_width(ui_MinuteNumRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MinuteNumRoller, 2);
    lv_obj_set_y(ui_MinuteNumRoller, -30);
    lv_obj_set_align(ui_MinuteNumRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_MinuteNumRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinuteNumRoller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinuteNumRoller, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MinuteNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinuteNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinuteNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinuteNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MinuteNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MinuteNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MinuteNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_MinuteNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinuteNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MinuteNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinuteNumRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MinuteNumRoller, lv_color_hex(0x0064FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MinuteNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MinuteNumRoller, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MinuteNumRoller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_SecondNumRoller = lv_roller_create(ui_TimeSetPage);
    lv_roller_set_options(ui_SecondNumRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_SecondNumRoller, 130);
    lv_obj_set_width(ui_SecondNumRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SecondNumRoller, 80);
    lv_obj_set_y(ui_SecondNumRoller, -30);
    lv_obj_set_align(ui_SecondNumRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_SecondNumRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SecondNumRoller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SecondNumRoller, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SecondNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecondNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SecondNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SecondNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SecondNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SecondNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SecondNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SecondNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SecondNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SecondNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecondNumRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SecondNumRoller, lv_color_hex(0x0064FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SecondNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SecondNumRoller, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SecondNumRoller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_HourMinColonLabel = lv_label_create(ui_TimeSetPage);
    lv_obj_set_width(ui_HourMinColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourMinColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourMinColonLabel, -38);
    lv_obj_set_y(ui_HourMinColonLabel, -33);
    lv_obj_set_align(ui_HourMinColonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourMinColonLabel, ":");
    lv_obj_set_style_text_font(ui_HourMinColonLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinSecColonLabel = lv_label_create(ui_TimeSetPage);
    lv_obj_set_width(ui_MinSecColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinSecColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinSecColonLabel, 40);
    lv_obj_set_y(ui_MinSecColonLabel, -32);
    lv_obj_set_align(ui_MinSecColonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinSecColonLabel, ":");
    lv_obj_set_style_text_font(ui_MinSecColonLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_obj_add_event_cb(ui_TimeSetOKButton,set_ok_button_event_cb,LV_EVENT_CLICKED,NULL);
    lv_obj_add_event_cb(ui_TimeSetPage,time_set_page_event_cb,LV_EVENT_GESTURE,NULL);
    
}

void ui_TimeSetPage_screen_destroy(void)
{
    if(ui_TimeSetPage) lv_obj_del(ui_TimeSetPage);

    // NULL screen variables
    ui_TimeSetPage = NULL;
    ui_HourNumRoller = NULL;
    ui_TimeSetOKButton = NULL;
    ui_DateSetOKIconLabel1 = NULL;
    ui_MinuteNumRoller = NULL;
    ui_SecondNumRoller = NULL;
    ui_HourMinColonLabel = NULL;
    ui_MinSecColonLabel = NULL;

}

static void time_set_page_init()
{
	ui_TimeSetPage_screen_init();
}

static void time_set_page_deinit()
{
	ui_TimeSetPage_screen_destroy();
}

static void time_set_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void time_set_page_pause()
{
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_time_set = 
{
	.page_obj = &ui_TimeSetPage,
	.init = time_set_page_init,
	.deinit = time_set_page_deinit,
	.resume = time_set_page_resume,
	.pause = time_set_page_pause,
};
