// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: testpage

#include "../ui.h"

lv_obj_t * ui_ChargePage = NULL;
lv_obj_t * ui_ChargPageBatNum = NULL;
lv_obj_t * ui_ChargPagebHourLabel = NULL;
lv_obj_t * ui_ChargPagebMinLabel = NULL;
lv_obj_t * ui_ChargPageTimePoint = NULL;
lv_obj_t * ui_CharPageBatArc = NULL;
lv_obj_t * ui_ChargPageBatIcon = NULL;
// event funtions

// build funtions

void ui_ChargePage_screen_init(void)
{
    ui_ChargePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ChargePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChargPageBatNum = lv_label_create(ui_ChargePage);
    lv_obj_set_width(ui_ChargPageBatNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPageBatNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargPageBatNum, -70);
    lv_obj_set_y(ui_ChargPageBatNum, -23);
    lv_obj_set_align(ui_ChargPageBatNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargPageBatNum, "50%");
    lv_obj_set_style_text_color(ui_ChargPageBatNum, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPageBatNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPageBatNum, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargPagebHourLabel = lv_label_create(ui_ChargePage);
    lv_obj_set_width(ui_ChargPagebHourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPagebHourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargPagebHourLabel, 59);
    lv_obj_set_y(ui_ChargPagebHourLabel, -73);
    lv_obj_set_align(ui_ChargPagebHourLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargPagebHourLabel, "11");
    lv_obj_set_style_text_color(ui_ChargPagebHourLabel, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPagebHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPagebHourLabel, &ui_font_OpenSasnsItalic100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ChargPagebHourLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ChargPagebHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChargPagebHourLabel, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargPagebMinLabel = lv_label_create(ui_ChargePage);
    lv_obj_set_width(ui_ChargPagebMinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPagebMinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargPagebMinLabel, 56);
    lv_obj_set_y(ui_ChargPagebMinLabel, 44);
    lv_obj_set_align(ui_ChargPagebMinLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargPagebMinLabel, "03");
    lv_obj_set_style_text_color(ui_ChargPagebMinLabel, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPagebMinLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPagebMinLabel, &ui_font_OpenSasnsItalic100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargPageTimePoint = lv_label_create(ui_ChargePage);
    lv_obj_set_width(ui_ChargPageTimePoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPageTimePoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargPageTimePoint, -24);
    lv_obj_set_y(ui_ChargPageTimePoint, 37);
    lv_obj_set_align(ui_ChargPageTimePoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargPageTimePoint, ":");
    lv_obj_set_style_text_color(ui_ChargPageTimePoint, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPageTimePoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPageTimePoint, &ui_font_OpenSasnsItalic100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharPageBatArc = lv_arc_create(ui_ChargePage);
    lv_obj_set_width(ui_CharPageBatArc, 60);
    lv_obj_set_height(ui_CharPageBatArc, 60);
    lv_obj_set_x(ui_CharPageBatArc, -70);
    lv_obj_set_y(ui_CharPageBatArc, -75);
    lv_obj_set_align(ui_CharPageBatArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CharPageBatArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_CharPageBatArc, 50);
    lv_arc_set_bg_angles(ui_CharPageBatArc, 90, 440);
    lv_obj_set_style_arc_width(ui_CharPageBatArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_CharPageBatArc, lv_color_hex(0x00FF7F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CharPageBatArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CharPageBatArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CharPageBatArc, lv_color_hex(0x00FF7F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CharPageBatArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CharPageBatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CharPageBatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CharPageBatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CharPageBatArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ChargPageBatIcon = lv_label_create(ui_CharPageBatArc);
    lv_obj_set_width(ui_ChargPageBatIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargPageBatIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ChargPageBatIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargPageBatIcon, "");
    lv_obj_set_style_text_color(ui_ChargPageBatIcon, lv_color_hex(0x00FF7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargPageBatIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargPageBatIcon, &ui_font_HPiconfont25, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ChargePage_screen_destroy(void)
{
    if(ui_ChargePage) lv_obj_del(ui_ChargePage);

    // NULL screen variables
    ui_ChargePage = NULL;
    ui_ChargPageBatNum = NULL;
    ui_ChargPagebHourLabel = NULL;
    ui_ChargPagebMinLabel = NULL;
    ui_ChargPageTimePoint = NULL;
    ui_CharPageBatArc = NULL;
    ui_ChargPageBatIcon = NULL;

}
