// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: testpage

#ifndef UI_HOMEPAGE_H
#define UI_HOMEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomePage
extern void ui_HomePage_screen_init(void);
extern void ui_HomePage_screen_destroy(void);
extern lv_obj_t * ui_HomePage;
extern lv_obj_t * ui_BatLabel;
extern lv_obj_t * ui_StepNumLabel;
extern lv_obj_t * ui_HRNumLabel;
extern lv_obj_t * ui_BatNumLabel;
extern lv_obj_t * ui_TimeHourLabel;
extern lv_obj_t * ui_TimeMinuteLabel;
extern lv_obj_t * ui_HRBPMArc;
extern lv_obj_t * ui_HRBPMIconLabel;
extern lv_obj_t * ui_StepArc;
extern lv_obj_t * ui_StepIconLabel;
extern lv_obj_t * ui_BatArc;
extern lv_obj_t * ui_BatIconLabel;
extern lv_obj_t * ui_DateButton;
extern lv_obj_t * ui_DayLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_StepsLabel;
extern lv_obj_t * ui_HRBPMLabel;
extern lv_obj_t * ui_DropDownPanel;
extern lv_obj_t * ui_UpBGPanel;
extern lv_obj_t * ui_NFCButton;
extern lv_obj_t * ui_NFCLabel;
extern lv_obj_t * ui_BLEButton;
extern lv_obj_t * ui_BLELabel;
extern lv_obj_t * ui_PowerButton;
extern lv_obj_t * ui_PowerLabel;
extern lv_obj_t * ui_SetButton;
extern lv_obj_t * ui_SetLabel;
extern lv_obj_t * ui_LightSlider;
extern lv_obj_t * ui_LightLabel;
extern lv_obj_t * ui_DownBGPanel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

