// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: AboutPage

#ifndef UI_ABOUTPAGE_H
#define UI_ABOUTPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"
// SCREEN: ui_AboutPage
extern void ui_AboutPage_screen_init(void);
extern void ui_AboutPage_screen_destroy(void);
extern lv_obj_t * ui_AboutPage;
extern lv_obj_t * ui_NameLabel;
extern lv_obj_t * ui_NameTextLabel;
extern lv_obj_t * ui_VersionLabel;
extern lv_obj_t * ui_VersionTextLabel;
extern lv_obj_t * ui_MCULabel;
extern lv_obj_t * ui_MCUTextLabel;
extern lv_obj_t * ui_OSLabel;
extern lv_obj_t * ui_OSTextLabel;
extern lv_obj_t * ui_UILabel;
extern lv_obj_t * ui_UITextLabel;
// CUSTOM VARIABLES

extern page_t page_about;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

