// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: CompassPage

#ifndef UI_COMPASSPAGE_H
#define UI_COMPASSPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"

// SCREEN: ui_CompassPage
extern void ui_CompassPage_screen_init(void);
extern void ui_CompassPage_screen_destroy(void);
extern lv_obj_t * ui_CompassPage;
extern lv_obj_t * ui_CompassPageImg;

extern lv_obj_t * ui_CompassAngleBtn;
extern lv_obj_t * ui_AngleIconLabel;
extern lv_obj_t * ui_AngelColonIcon;
extern lv_obj_t * ui_AngelNum;
extern lv_obj_t * ui_CompassAltitudeBtn;
extern lv_obj_t * ui_AltitudeIconLabel;
extern lv_obj_t * ui_AltitudeColonIcon;
extern lv_obj_t * ui_AltitudeNum;
// CUSTOM VARIABLES

LV_IMG_DECLARE(ui_img_compass_needle_png);

extern page_t page_compass;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

