// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: testpage

#ifndef UI_CHARGEPAGE_H
#define UI_CHARGEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"

// SCREEN: ui_ChargePage
extern void ui_ChargePage_screen_init(void);
extern void ui_ChargePage_screen_destroy(void);
extern lv_obj_t * ui_ChargePage;
extern lv_obj_t * ui_ChargPageBatNum;
extern lv_obj_t * ui_ChargPagebHourLabel;
extern lv_obj_t * ui_ChargPagebMinLabel;
extern lv_obj_t * ui_ChargPageTimePoint;
extern lv_obj_t * ui_CharPageBatArc;
extern lv_obj_t * ui_ChargPageBatIcon;
// CUSTOM VARIABLES

extern page_t page_charge;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

