// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: CalendarPage

#ifndef UI_CALENDARPAGE_H
#define UI_CALENDARPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"

// SCREEN: ui_CalendarPage
extern void ui_CalendarPage_screen_init(void);
extern void ui_CalendarPage_screen_destroy(void);
extern lv_obj_t * ui_CalendarPage;
extern lv_obj_t * ui_Calendar;
// CUSTOM VARIABLES

extern page_t page_calendar;	

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

