// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#ifndef UI_DATESETPAGE_H
#define UI_DATESETPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"
// SCREEN: ui_DateSetPage
extern void ui_DateSetPage_screen_init(void);
extern void ui_DateSetPage_screen_destroy(void);
extern lv_obj_t * ui_DateSetPage;
extern lv_obj_t * ui_YearNumRoller;
extern lv_obj_t * ui_DateSetOKButton;
extern lv_obj_t * ui_DateSetOKIconLabel;
extern lv_obj_t * ui_MonthNumRoller;
extern lv_obj_t * ui_DayNumRoller;
extern lv_obj_t * ui_YearMonColonLabel;
extern lv_obj_t * ui_MonDayColonLabel;
// CUSTOM VARIABLES

extern page_t page_date_set;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

