// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: EnvironmentPage

#ifndef UI_ENVIRONMENTPAGE_H
#define UI_ENVIRONMENTPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"

// SCREEN: ui_EnvironmentPage
extern void ui_EnvironmentPage_screen_init(void);
extern void ui_EnvironmentPage_screen_destroy(void);
extern lv_obj_t * ui_EnvironmentPage;
extern lv_obj_t * ui_EnvLabel;
extern lv_obj_t * ui_TempBar;
extern lv_obj_t * ui_HumBar;
extern lv_obj_t * ui_EnvTempIconLabel;
extern lv_obj_t * ui_EnvHumIconLabel;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_HumLabel;
// CUSTOM VARIABLES

#define TEMP_RANGE_LOW -20
#define TEMP_RANGE_HIGH 50

#define HUM_RANGE_LOW 0
#define HUM_RANGE_HIGH 100

extern page_t page_env;



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

