// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: testpage

#ifndef UI_HOMEPAGE_H
#define UI_HOMEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"

	
// SCREEN: ui_HomePage
extern void ui_HomePage_screen_init(void);
extern void ui_HomePage_screen_destroy(void);
extern lv_obj_t * ui_HomePage;
extern lv_obj_t * ui_BatLabel;
extern lv_obj_t * ui_StepNumLabel;
extern lv_obj_t * ui_HRNumLabel;
extern lv_obj_t * ui_BatNumLabel;
extern lv_obj_t * ui_TimeHourLabel;
extern lv_obj_t * ui_TimeMinuteLabel;
extern lv_obj_t * ui_HRBPMArc;
extern lv_obj_t * ui_HRBPMIconLabel;
extern lv_obj_t * ui_StepArc;
extern lv_obj_t * ui_StepIconLabel;
extern lv_obj_t * ui_BatArc;
extern lv_obj_t * ui_BatIconLabel;
extern lv_obj_t * ui_DateButton;
extern lv_obj_t * ui_DayLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_StepsLabel;
extern lv_obj_t * ui_HRBPMLabel;
// CUSTOM VARIABLES


extern uint8_t ui_TimeHourValue;
extern uint8_t ui_TimeMinuteValue;
extern uint8_t ui_DateMonthValue;   
extern uint8_t ui_DateDayValue;
extern uint8_t ui_DataWeekdayValue;
extern uint8_t ui_BatArcValue;

extern page_t page_home; // 主页面

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

