// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#ifndef UI_LTSETPAGE_H
#define UI_LTSETPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"

// SCREEN: ui_LTSetPage
extern void ui_LTSetPage_screen_init(void);
extern void ui_LTSetPage_screen_destroy(void);
extern lv_obj_t * ui_LTSetPage;
extern lv_obj_t * ui_LTimeNumRoller;
extern lv_obj_t * ui_LTimeSecondLabel;
extern lv_obj_t * ui_LTimeIconLabel;
extern lv_obj_t * ui_LTimeSetOKButton;
extern lv_obj_t * ui_LTimeSetOKIconLabel;
// CUSTOM VARIABLES

extern page_t page_light_time_set_page;

extern uint8_t light_time_value; // 全局变量，保存当前选择的常亮时间值，单位为秒

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

