// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SettingPage

#ifndef UI_SETTINGPAGE_H
#define UI_SETTINGPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"

// SCREEN: ui_SettingPage
extern void ui_SettingPage_screen_init(void);
extern void ui_SettingPage_screen_destroy(void);
extern lv_obj_t * ui_SettingMenuPage;
extern lv_obj_t * ui_MenuLightTimePanel;
extern lv_obj_t * ui_LightTimeButton;
extern lv_obj_t * ui_LightTimeIconLabel;
extern lv_obj_t * ui_LightTimeLabel;
extern lv_obj_t * ui_MenuScrrenOffPanel;
extern lv_obj_t * ui_ScrrenOffButton;
extern lv_obj_t * ui_ScrrenOffIconLabel;
extern lv_obj_t * ui_ScrrenOffLabel;
extern lv_obj_t * ui_MenuDataTimePanel;
extern lv_obj_t * ui_DataTimeButton;
extern lv_obj_t * ui_DataTimeIconLabel;
extern lv_obj_t * ui_DataTimeLabel;
extern lv_obj_t * ui_MenuWristUpPanel;
extern lv_obj_t * ui_WristUpButton;
extern lv_obj_t * ui_WristUpIconLabel;
extern lv_obj_t * ui_WristUpLabel;
extern lv_obj_t * ui_WristUpSwitch;
extern lv_obj_t * ui_MenuPwdSetPanel;
extern lv_obj_t * ui_PwdSetButton;
extern lv_obj_t * ui_PwdSetIconLabel;
extern lv_obj_t * ui_PwdSetLabel;
// CUSTOM VARIABLES

extern page_t page_setting_menu;


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

