// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: TimerPage

#ifndef UI_TIMERPAGE_H
#define UI_TIMERPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TimerPage
extern void ui_TimerPage_screen_init(void);
extern void ui_TimerPage_screen_destroy(void);
extern lv_obj_t * ui_TimerPage;
extern lv_obj_t * ui_StartButton;
extern lv_obj_t * ui_StartIconLabel;
extern lv_obj_t * ui_ReButton;
extern lv_obj_t * ui_ReIconLabel;
extern lv_obj_t * ui_TimerMinLabel;
extern lv_obj_t * ui_TimerColonLabel;
extern lv_obj_t * ui_TimerSecLabel;
extern lv_obj_t * ui_TimerPointLabel;
extern lv_obj_t * ui_TimerMilSecLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

