// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: TimerPage

#include "../ui.h"

lv_obj_t * ui_TimerPage = NULL;
lv_obj_t * ui_StartButton = NULL;
lv_obj_t * ui_StartIconLabel = NULL;
lv_obj_t * ui_ReButton = NULL;
lv_obj_t * ui_ReIconLabel = NULL;
lv_obj_t * ui_TimerMinLabel = NULL;
lv_obj_t * ui_TimerColonLabel = NULL;
lv_obj_t * ui_TimerSecLabel = NULL;
lv_obj_t * ui_TimerPointLabel = NULL;
lv_obj_t * ui_TimerMilSecLabel = NULL;
// event funtions

// build funtions

void ui_TimerPage_screen_init(void)
{
    ui_TimerPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TimerPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StartButton = lv_button_create(ui_TimerPage);
    lv_obj_set_width(ui_StartButton, 60);
    lv_obj_set_height(ui_StartButton, 60);
    lv_obj_set_x(ui_StartButton, 40);
    lv_obj_set_y(ui_StartButton, 50);
    lv_obj_set_align(ui_StartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StartButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartIconLabel = lv_label_create(ui_StartButton);
    lv_obj_set_width(ui_StartIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartIconLabel, "");
    lv_obj_set_style_text_font(ui_StartIconLabel, &ui_font_TMPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReButton = lv_button_create(ui_TimerPage);
    lv_obj_set_width(ui_ReButton, 60);
    lv_obj_set_height(ui_ReButton, 60);
    lv_obj_set_x(ui_ReButton, -40);
    lv_obj_set_y(ui_ReButton, 50);
    lv_obj_set_align(ui_ReButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ReButton, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReIconLabel = lv_label_create(ui_ReButton);
    lv_obj_set_width(ui_ReIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReIconLabel, "");
    lv_obj_set_style_text_font(ui_ReIconLabel, &ui_font_TMPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerMinLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerMinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerMinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerMinLabel, -69);
    lv_obj_set_y(ui_TimerMinLabel, -20);
    lv_obj_set_align(ui_TimerMinLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerMinLabel, "00");
    lv_obj_set_style_text_font(ui_TimerMinLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerColonLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerColonLabel, -32);
    lv_obj_set_y(ui_TimerColonLabel, -24);
    lv_obj_set_align(ui_TimerColonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerColonLabel, ":");
    lv_obj_set_style_text_font(ui_TimerColonLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerSecLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerSecLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerSecLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerSecLabel, 6);
    lv_obj_set_y(ui_TimerSecLabel, -20);
    lv_obj_set_align(ui_TimerSecLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerSecLabel, "00");
    lv_obj_set_style_text_font(ui_TimerSecLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerPointLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerPointLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerPointLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerPointLabel, 38);
    lv_obj_set_y(ui_TimerPointLabel, -20);
    lv_obj_set_align(ui_TimerPointLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerPointLabel, ".");
    lv_obj_set_style_text_font(ui_TimerPointLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerMilSecLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerMilSecLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerMilSecLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerMilSecLabel, 71);
    lv_obj_set_y(ui_TimerMilSecLabel, -20);
    lv_obj_set_align(ui_TimerMilSecLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerMilSecLabel, "00");
    lv_obj_set_style_text_font(ui_TimerMilSecLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_TimerPage_screen_destroy(void)
{
    if(ui_TimerPage) lv_obj_del(ui_TimerPage);

    // NULL screen variables
    ui_TimerPage = NULL;
    ui_StartButton = NULL;
    ui_StartIconLabel = NULL;
    ui_ReButton = NULL;
    ui_ReIconLabel = NULL;
    ui_TimerMinLabel = NULL;
    ui_TimerColonLabel = NULL;
    ui_TimerSecLabel = NULL;
    ui_TimerPointLabel = NULL;
    ui_TimerMilSecLabel = NULL;

}
