// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#include "../ui.h"

lv_obj_t * ui_AllSettingPages = NULL;
// event funtions

// build funtions

void ui_AllSettingPages_screen_init(void)
{
    ui_AllSettingPages = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AllSettingPages, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_AllSettingPages_screen_destroy(void)
{
    if(ui_AllSettingPages) lv_obj_del(ui_AllSettingPages);

    // NULL screen variables
    ui_AllSettingPages = NULL;

}
