// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#ifndef UI_DATETIMEMENUPAGE_H
#define UI_DATETIMEMENUPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DateTimeMenuPage
extern void ui_DateTimeMenuPage_screen_init(void);
extern void ui_DateTimeMenuPage_screen_destroy(void);
extern lv_obj_t * ui_DateTimeMenuPage;
extern lv_obj_t * ui_SyncAppPanel;
extern lv_obj_t * ui_SyncAppLabel;
extern lv_obj_t * ui_SyncAppSwitch;
extern lv_obj_t * ui_MenuDateSetPanel;
extern lv_obj_t * ui_MenuDateSetLabel;
extern lv_obj_t * ui_PointLabel1;
extern lv_obj_t * ui_PointLabel2;
extern lv_obj_t * ui_PointLabel3;
extern lv_obj_t * ui_MenuTimeSetPanel;
extern lv_obj_t * ui_MenuTimeSetLabel;
extern lv_obj_t * ui_PointLabel5;
extern lv_obj_t * ui_PointLabel6;
extern lv_obj_t * ui_PointLabel7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

