// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#include "../ui.h"

lv_obj_t * ui_DateSetPage = NULL;
lv_obj_t * ui_YearNumRoller = NULL;
lv_obj_t * ui_DateSetOKButton = NULL;
lv_obj_t * ui_DateSetOKIconLabel = NULL;
lv_obj_t * ui_MonthNumRoller = NULL;
lv_obj_t * ui_DayNumRoller = NULL;
lv_obj_t * ui_YearMonColonLabel = NULL;
lv_obj_t * ui_MonDayColonLabel = NULL;
// event funtions

// build funtions

void ui_DateSetPage_screen_init(void)
{
    ui_DateSetPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DateSetPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_YearNumRoller = lv_roller_create(ui_DateSetPage);
    lv_roller_set_options(ui_YearNumRoller, "2025\n2026\n2027\n2028\n2029\n2030\n2031\n2032\n2033\n2034\n2035",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_YearNumRoller, 130);
    lv_obj_set_width(ui_YearNumRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_YearNumRoller, -70);
    lv_obj_set_y(ui_YearNumRoller, -30);
    lv_obj_set_align(ui_YearNumRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_YearNumRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_YearNumRoller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_YearNumRoller, &ui_font_CuYuan30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_YearNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YearNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_YearNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_YearNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_YearNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_YearNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_YearNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_YearNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_YearNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_YearNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YearNumRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_YearNumRoller, lv_color_hex(0x0064FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_YearNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_YearNumRoller, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_YearNumRoller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_DateSetOKButton = lv_button_create(ui_DateSetPage);
    lv_obj_set_width(ui_DateSetOKButton, 240);
    lv_obj_set_height(ui_DateSetOKButton, 50);
    lv_obj_set_align(ui_DateSetOKButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_DateSetOKButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DateSetOKButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DateSetOKButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DateSetOKButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DateSetOKButton, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DateSetOKButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_DateSetOKButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_DateSetOKIconLabel = lv_label_create(ui_DateSetOKButton);
    lv_obj_set_width(ui_DateSetOKIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateSetOKIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DateSetOKIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateSetOKIconLabel, "");
    lv_obj_set_style_text_font(ui_DateSetOKIconLabel, &ui_font_LTSiconfont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonthNumRoller = lv_roller_create(ui_DateSetPage);
    lv_roller_set_options(ui_MonthNumRoller, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_MonthNumRoller, 130);
    lv_obj_set_width(ui_MonthNumRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MonthNumRoller, 15);
    lv_obj_set_y(ui_MonthNumRoller, -30);
    lv_obj_set_align(ui_MonthNumRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_MonthNumRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MonthNumRoller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MonthNumRoller, &ui_font_CuYuan30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MonthNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonthNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MonthNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MonthNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MonthNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MonthNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MonthNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_MonthNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MonthNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MonthNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MonthNumRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MonthNumRoller, lv_color_hex(0x0064FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MonthNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MonthNumRoller, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MonthNumRoller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_DayNumRoller = lv_roller_create(ui_DateSetPage);
    lv_roller_set_options(ui_DayNumRoller,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_DayNumRoller, 130);
    lv_obj_set_width(ui_DayNumRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_DayNumRoller, 85);
    lv_obj_set_y(ui_DayNumRoller, -30);
    lv_obj_set_align(ui_DayNumRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_DayNumRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DayNumRoller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DayNumRoller, &ui_font_CuYuan30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DayNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DayNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DayNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DayNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DayNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DayNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DayNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_DayNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DayNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DayNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DayNumRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DayNumRoller, lv_color_hex(0x0064FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DayNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DayNumRoller, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DayNumRoller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_YearMonColonLabel = lv_label_create(ui_DateSetPage);
    lv_obj_set_width(ui_YearMonColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YearMonColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_YearMonColonLabel, -18);
    lv_obj_set_y(ui_YearMonColonLabel, -35);
    lv_obj_set_align(ui_YearMonColonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YearMonColonLabel, ":");
    lv_obj_set_style_text_font(ui_YearMonColonLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonDayColonLabel = lv_label_create(ui_DateSetPage);
    lv_obj_set_width(ui_MonDayColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MonDayColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MonDayColonLabel, 48);
    lv_obj_set_y(ui_MonDayColonLabel, -35);
    lv_obj_set_align(ui_MonDayColonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MonDayColonLabel, ":");
    lv_obj_set_style_text_font(ui_MonDayColonLabel, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_DateSetPage_screen_destroy(void)
{
    if(ui_DateSetPage) lv_obj_del(ui_DateSetPage);

    // NULL screen variables
    ui_DateSetPage = NULL;
    ui_YearNumRoller = NULL;
    ui_DateSetOKButton = NULL;
    ui_DateSetOKIconLabel = NULL;
    ui_MonthNumRoller = NULL;
    ui_DayNumRoller = NULL;
    ui_YearMonColonLabel = NULL;
    ui_MonDayColonLabel = NULL;

}
