// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#include "../ui.h"

lv_obj_t * ui_DateTimeMenuPage = NULL;
lv_obj_t * ui_SyncAppPanel = NULL;
lv_obj_t * ui_SyncAppLabel = NULL;
lv_obj_t * ui_SyncAppSwitch = NULL;
lv_obj_t * ui_MenuDateSetPanel = NULL;
lv_obj_t * ui_MenuDateSetLabel = NULL;
lv_obj_t * ui_PointLabel1 = NULL;
lv_obj_t * ui_PointLabel2 = NULL;
lv_obj_t * ui_PointLabel3 = NULL;
lv_obj_t * ui_MenuTimeSetPanel = NULL;
lv_obj_t * ui_MenuTimeSetLabel = NULL;
lv_obj_t * ui_PointLabel5 = NULL;
lv_obj_t * ui_PointLabel6 = NULL;
lv_obj_t * ui_PointLabel7 = NULL;
// event funtions

// build funtions

void ui_DateTimeMenuPage_screen_init(void)
{
    ui_DateTimeMenuPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DateTimeMenuPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_DateTimeMenuPage, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DateTimeMenuPage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_SyncAppPanel = lv_obj_create(ui_DateTimeMenuPage);
    lv_obj_set_width(ui_SyncAppPanel, 240);
    lv_obj_set_height(ui_SyncAppPanel, 63);
    lv_obj_set_x(ui_SyncAppPanel, -59);
    lv_obj_set_y(ui_SyncAppPanel, -105);
    lv_obj_set_align(ui_SyncAppPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SyncAppPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SyncAppPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SyncAppPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SyncAppPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SyncAppPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SyncAppPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SyncAppLabel = lv_label_create(ui_SyncAppPanel);
    lv_obj_set_width(ui_SyncAppLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SyncAppLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SyncAppLabel, 10);
    lv_obj_set_y(ui_SyncAppLabel, 0);
    lv_obj_set_align(ui_SyncAppLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SyncAppLabel, "同步APP");
    lv_obj_set_style_text_font(ui_SyncAppLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SyncAppSwitch = lv_switch_create(ui_SyncAppPanel);
    lv_obj_set_width(ui_SyncAppSwitch, 70);
    lv_obj_set_height(ui_SyncAppSwitch, 30);
    lv_obj_set_align(ui_SyncAppSwitch, LV_ALIGN_RIGHT_MID);

    ui_MenuDateSetPanel = lv_obj_create(ui_DateTimeMenuPage);
    lv_obj_set_width(ui_MenuDateSetPanel, 240);
    lv_obj_set_height(ui_MenuDateSetPanel, 63);
    lv_obj_set_x(ui_MenuDateSetPanel, -63);
    lv_obj_set_y(ui_MenuDateSetPanel, -34);
    lv_obj_set_align(ui_MenuDateSetPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MenuDateSetPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuDateSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuDateSetPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuDateSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuDateSetPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuDateSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuDateSetPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuDateSetPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuDateSetLabel = lv_label_create(ui_MenuDateSetPanel);
    lv_obj_set_width(ui_MenuDateSetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuDateSetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuDateSetLabel, 10);
    lv_obj_set_y(ui_MenuDateSetLabel, 0);
    lv_obj_set_align(ui_MenuDateSetLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MenuDateSetLabel, "日期设置");
    lv_obj_set_style_text_font(ui_MenuDateSetLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PointLabel1 = lv_label_create(ui_MenuDateSetPanel);
    lv_obj_set_width(ui_PointLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PointLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PointLabel1, 0);
    lv_obj_set_y(ui_PointLabel1, -10);
    lv_obj_set_align(ui_PointLabel1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_PointLabel1, ".");
    lv_obj_set_style_text_font(ui_PointLabel1, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PointLabel2 = lv_label_create(ui_MenuDateSetPanel);
    lv_obj_set_width(ui_PointLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PointLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PointLabel2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_PointLabel2, ".");
    lv_obj_set_style_text_font(ui_PointLabel2, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PointLabel3 = lv_label_create(ui_MenuDateSetPanel);
    lv_obj_set_width(ui_PointLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PointLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PointLabel3, 0);
    lv_obj_set_y(ui_PointLabel3, 10);
    lv_obj_set_align(ui_PointLabel3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_PointLabel3, ".");
    lv_obj_set_style_text_font(ui_PointLabel3, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuTimeSetPanel = lv_obj_create(ui_DateTimeMenuPage);
    lv_obj_set_width(ui_MenuTimeSetPanel, 240);
    lv_obj_set_height(ui_MenuTimeSetPanel, 63);
    lv_obj_set_x(ui_MenuTimeSetPanel, -41);
    lv_obj_set_y(ui_MenuTimeSetPanel, 30);
    lv_obj_set_align(ui_MenuTimeSetPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MenuTimeSetPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuTimeSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuTimeSetPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuTimeSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuTimeSetPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuTimeSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuTimeSetPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuTimeSetPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuTimeSetLabel = lv_label_create(ui_MenuTimeSetPanel);
    lv_obj_set_width(ui_MenuTimeSetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuTimeSetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuTimeSetLabel, 10);
    lv_obj_set_y(ui_MenuTimeSetLabel, 0);
    lv_obj_set_align(ui_MenuTimeSetLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MenuTimeSetLabel, "时间设置");
    lv_obj_set_style_text_font(ui_MenuTimeSetLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PointLabel5 = lv_label_create(ui_MenuTimeSetPanel);
    lv_obj_set_width(ui_PointLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PointLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PointLabel5, 0);
    lv_obj_set_y(ui_PointLabel5, -10);
    lv_obj_set_align(ui_PointLabel5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_PointLabel5, ".");
    lv_obj_set_style_text_font(ui_PointLabel5, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PointLabel6 = lv_label_create(ui_MenuTimeSetPanel);
    lv_obj_set_width(ui_PointLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PointLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PointLabel6, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_PointLabel6, ".");
    lv_obj_set_style_text_font(ui_PointLabel6, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PointLabel7 = lv_label_create(ui_MenuTimeSetPanel);
    lv_obj_set_width(ui_PointLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PointLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PointLabel7, 0);
    lv_obj_set_y(ui_PointLabel7, 10);
    lv_obj_set_align(ui_PointLabel7, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_PointLabel7, ".");
    lv_obj_set_style_text_font(ui_PointLabel7, &ui_font_CuYuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_DateTimeMenuPage_screen_destroy(void)
{
    if(ui_DateTimeMenuPage) lv_obj_del(ui_DateTimeMenuPage);

    // NULL screen variables
    ui_DateTimeMenuPage = NULL;
    ui_SyncAppPanel = NULL;
    ui_SyncAppLabel = NULL;
    ui_SyncAppSwitch = NULL;
    ui_MenuDateSetPanel = NULL;
    ui_MenuDateSetLabel = NULL;
    ui_PointLabel1 = NULL;
    ui_PointLabel2 = NULL;
    ui_PointLabel3 = NULL;
    ui_MenuTimeSetPanel = NULL;
    ui_MenuTimeSetLabel = NULL;
    ui_PointLabel5 = NULL;
    ui_PointLabel6 = NULL;
    ui_PointLabel7 = NULL;

}
