// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#include "../ui.h"

lv_obj_t * ui_LTSetPage = NULL;
lv_obj_t * ui_LTimeNumRoller = NULL;
lv_obj_t * ui_LTimeSecondLabel = NULL;
lv_obj_t * ui_LTimeIconLabel = NULL;
lv_obj_t * ui_LTimeSetOKButton = NULL;
lv_obj_t * ui_LTimeSetOKIconLabel = NULL;
// event funtions

// build funtions

void ui_LTSetPage_screen_init(void)
{
    ui_LTSetPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LTSetPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LTimeNumRoller = lv_roller_create(ui_LTSetPage);
    lv_roller_set_options(ui_LTimeNumRoller, "10\n15\n20\n30\n45\n60", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_LTimeNumRoller, 150);
    lv_obj_set_width(ui_LTimeNumRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_LTimeNumRoller, -1);
    lv_obj_set_y(ui_LTimeNumRoller, -22);
    lv_obj_set_align(ui_LTimeNumRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_LTimeNumRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LTimeNumRoller, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LTimeNumRoller, &ui_font_CuYuan40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LTimeNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LTimeNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LTimeNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LTimeNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LTimeNumRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LTimeNumRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LTimeNumRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_LTimeNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LTimeNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LTimeNumRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LTimeNumRoller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LTimeNumRoller, lv_color_hex(0x0064FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LTimeNumRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LTimeNumRoller, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LTimeNumRoller, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_LTimeSecondLabel = lv_label_create(ui_LTSetPage);
    lv_obj_set_width(ui_LTimeSecondLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LTimeSecondLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LTimeSecondLabel, 65);
    lv_obj_set_y(ui_LTimeSecondLabel, -22);
    lv_obj_set_align(ui_LTimeSecondLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LTimeSecondLabel, "秒");
    lv_obj_set_style_text_font(ui_LTimeSecondLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LTimeIconLabel = lv_label_create(ui_LTSetPage);
    lv_obj_set_width(ui_LTimeIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LTimeIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LTimeIconLabel, -1);
    lv_obj_set_y(ui_LTimeIconLabel, -109);
    lv_obj_set_align(ui_LTimeIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LTimeIconLabel, "");
    lv_obj_set_style_text_color(ui_LTimeIconLabel, lv_color_hex(0xF99A08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LTimeIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LTimeIconLabel, &ui_font_LTSiconfont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LTimeSetOKButton = lv_button_create(ui_LTSetPage);
    lv_obj_set_width(ui_LTimeSetOKButton, 240);
    lv_obj_set_height(ui_LTimeSetOKButton, 50);
    lv_obj_set_align(ui_LTimeSetOKButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_LTimeSetOKButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LTimeSetOKButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LTimeSetOKButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LTimeSetOKButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LTimeSetOKButton, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LTimeSetOKButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LTimeSetOKButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LTimeSetOKIconLabel = lv_label_create(ui_LTimeSetOKButton);
    lv_obj_set_width(ui_LTimeSetOKIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LTimeSetOKIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LTimeSetOKIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LTimeSetOKIconLabel, "");
    lv_obj_set_style_text_font(ui_LTimeSetOKIconLabel, &ui_font_LTSiconfont40, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_LTSetPage_screen_destroy(void)
{
    if(ui_LTSetPage) lv_obj_del(ui_LTSetPage);

    // NULL screen variables
    ui_LTSetPage = NULL;
    ui_LTimeNumRoller = NULL;
    ui_LTimeSecondLabel = NULL;
    ui_LTimeIconLabel = NULL;
    ui_LTimeSetOKButton = NULL;
    ui_LTimeSetOKIconLabel = NULL;

}
