// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#ifndef UI_SOFFTIMESETPAGE_H
#define UI_SOFFTIMESETPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SOffTimeSetPage
extern void ui_SOffTimeSetPage_screen_init(void);
extern void ui_SOffTimeSetPage_screen_destroy(void);
extern lv_obj_t * ui_SOffTimeSetPage;
extern lv_obj_t * ui_SOffTimeNumRoller;
extern lv_obj_t * ui_SOffSecondLabel;
extern lv_obj_t * ui_SOffTimeIconLabel;
extern lv_obj_t * ui_SOffTimeSetOKButton;
extern lv_obj_t * ui_SOffTimeSetOKIconLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

