// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#ifndef UI_TIMESETPAGE_H
#define UI_TIMESETPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TimeSetPage
extern void ui_TimeSetPage_screen_init(void);
extern void ui_TimeSetPage_screen_destroy(void);
extern lv_obj_t * ui_TimeSetPage;
extern lv_obj_t * ui_HourNumRoller;
extern lv_obj_t * ui_TimeSetOKButton;
extern lv_obj_t * ui_DateSetOKIconLabel1;
extern lv_obj_t * ui_MinuteNumRoller;
extern lv_obj_t * ui_SecondNumRoller;
extern lv_obj_t * ui_HourMinColonLabel;
extern lv_obj_t * ui_MinSecColonLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

