// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: EnvironmentPage

#include "ui_EnvironmentPage.h"

lv_obj_t * ui_EnvironmentPage = NULL;
lv_obj_t * ui_EnvLabel = NULL;
lv_obj_t * ui_TempBar = NULL;
lv_obj_t * ui_HumBar = NULL;
lv_obj_t * ui_EnvTempIconLabel = NULL;
lv_obj_t * ui_EnvHumIconLabel = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_HumLabel = NULL;
// event funtions

static void env_page_event_cb(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_GESTURE)
  {
			lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
			if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
      {
				 page_back();
      }
	}
}


// build funtions

void ui_EnvironmentPage_screen_init(void)
{
    ui_EnvironmentPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_EnvironmentPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EnvLabel = lv_label_create(ui_EnvironmentPage);
    lv_obj_set_width(ui_EnvLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnvLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EnvLabel, 2);
    lv_obj_set_y(ui_EnvLabel, -120);
    lv_obj_set_align(ui_EnvLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnvLabel, "环境温湿度");
    lv_obj_set_style_text_color(ui_EnvLabel, lv_color_hex(0x17EF77), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EnvLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EnvLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempBar = lv_bar_create(ui_EnvironmentPage);
    lv_bar_set_range(ui_TempBar, -20, 50);
    lv_bar_set_value(ui_TempBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TempBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TempBar, 20);
    lv_obj_set_height(ui_TempBar, 150);
    lv_obj_set_x(ui_TempBar, -43);
    lv_obj_set_y(ui_TempBar, 10);
    lv_obj_set_align(ui_TempBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TempBar, lv_color_hex(0x391010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TempBar, lv_color_hex(0xCC3031), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_TempBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_TempBar,
                                                                                              lv_obj_get_style_pad_right(ui_TempBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_HumBar = lv_bar_create(ui_EnvironmentPage);
    lv_bar_set_value(ui_HumBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HumBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HumBar, 20);
    lv_obj_set_height(ui_HumBar, 150);
    lv_obj_set_x(ui_HumBar, 42);
    lv_obj_set_y(ui_HumBar, 10);
    lv_obj_set_align(ui_HumBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_HumBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_HumBar,
                                                                                             lv_obj_get_style_pad_right(ui_HumBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_EnvTempIconLabel = lv_label_create(ui_EnvironmentPage);
    lv_obj_set_width(ui_EnvTempIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnvTempIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EnvTempIconLabel, -43);
    lv_obj_set_y(ui_EnvTempIconLabel, -82);
    lv_obj_set_align(ui_EnvTempIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnvTempIconLabel, "");
    lv_obj_set_style_text_color(ui_EnvTempIconLabel, lv_color_hex(0xCC3031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EnvTempIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EnvTempIconLabel, &ui_font_EPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnvHumIconLabel = lv_label_create(ui_EnvironmentPage);
    lv_obj_set_width(ui_EnvHumIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnvHumIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EnvHumIconLabel, 42);
    lv_obj_set_y(ui_EnvHumIconLabel, -84);
    lv_obj_set_align(ui_EnvHumIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnvHumIconLabel, "");
    lv_obj_set_style_text_color(ui_EnvHumIconLabel, lv_color_hex(0x2195F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EnvHumIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EnvHumIconLabel, &ui_font_EPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_EnvironmentPage);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, -28);
    lv_obj_set_y(ui_TempLabel, 110);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "25°");
    lv_obj_set_style_text_font(ui_TempLabel, &ui_font_CuYuan30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumLabel = lv_label_create(ui_EnvironmentPage);
    lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumLabel, 49);
    lv_obj_set_y(ui_HumLabel, 110);
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel, "50%");
    lv_obj_set_style_text_font(ui_HumLabel, &ui_font_CuYuan30, LV_PART_MAIN | LV_STATE_DEFAULT);

		lv_obj_add_event_cb(ui_EnvironmentPage,env_page_event_cb, LV_EVENT_GESTURE, NULL); // 点击回调函数
}

void ui_EnvironmentPage_screen_destroy(void)
{
    if(ui_EnvironmentPage) lv_obj_del(ui_EnvironmentPage);

    // NULL screen variables
    ui_EnvironmentPage = NULL;
    ui_EnvLabel = NULL;
    ui_TempBar = NULL;
    ui_HumBar = NULL;
    ui_EnvTempIconLabel = NULL;
    ui_EnvHumIconLabel = NULL;
    ui_TempLabel = NULL;
    ui_HumLabel = NULL;

}



static void env_page_init()
{
	ui_EnvironmentPage_screen_init();
}

static void env_page_deinit()
{
	ui_EnvironmentPage_screen_destroy();
}

static void env_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void env_page_pause()
{
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_env = 
{
	.page_obj = &ui_EnvironmentPage,
	.init = env_page_init,
	.deinit = env_page_deinit,
	.resume = env_page_resume,
	.pause = env_page_pause,
};
