// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: HeartRatePage

#include "ui_HeartRatePage.h"

lv_obj_t * ui_HeartRatePage = NULL;
lv_obj_t * ui_HeartRateIcon = NULL;
lv_obj_t * ui_TimesLabel = NULL;
lv_obj_t * ui_HeartRateNumLabel = NULL;
lv_obj_t * ui_MeasureLabel = NULL;
// event funtions


static void hr_page_event_cb(lv_event_t* e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_GESTURE)
	{
			lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
			if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
      {
				 page_back();
      }
	}
}


// build funtions

void ui_HeartRatePage_screen_init(void)
{
    ui_HeartRatePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HeartRatePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeartRateIcon = lv_label_create(ui_HeartRatePage);
    lv_obj_set_width(ui_HeartRateIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRateIcon, 0);
    lv_obj_set_y(ui_HeartRateIcon, -84);
    lv_obj_set_align(ui_HeartRateIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartRateIcon, "");
    lv_obj_set_style_text_color(ui_HeartRateIcon, lv_color_hex(0xD81E06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeartRateIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeartRateIcon, &ui_font_HRPiconfont50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimesLabel = lv_label_create(ui_HeartRatePage);
    lv_obj_set_width(ui_TimesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimesLabel, 84);
    lv_obj_set_y(ui_TimesLabel, 12);
    lv_obj_set_align(ui_TimesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimesLabel, "次/分");
    lv_obj_set_style_text_color(ui_TimesLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimesLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimesLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartRateNumLabel = lv_label_create(ui_HeartRatePage);
    lv_obj_set_width(ui_HeartRateNumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateNumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRateNumLabel, -2);
    lv_obj_set_y(ui_HeartRateNumLabel, 3);
    lv_obj_set_align(ui_HeartRateNumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartRateNumLabel, "100");
    lv_obj_set_style_text_font(ui_HeartRateNumLabel, &ui_font_CuYuan60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeasureLabel = lv_label_create(ui_HeartRatePage);
    lv_obj_set_width(ui_MeasureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureLabel, 4);
    lv_obj_set_y(ui_MeasureLabel, 79);
    lv_obj_set_align(ui_MeasureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureLabel, "正在测量...");
    lv_obj_set_style_text_color(ui_MeasureLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

		lv_obj_add_event_cb(ui_HeartRatePage,hr_page_event_cb, LV_EVENT_GESTURE, NULL); // 回调函数
}

void ui_HeartRatePage_screen_destroy(void)
{
    if(ui_HeartRatePage) lv_obj_del(ui_HeartRatePage);

    // NULL screen variables
    ui_HeartRatePage = NULL;
    ui_HeartRateIcon = NULL;
    ui_TimesLabel = NULL;
    ui_HeartRateNumLabel = NULL;
    ui_MeasureLabel = NULL;

}

static void heart_rate_page_init()
{
	ui_HeartRatePage_screen_init();
}

static void heart_rate_page_deinit()
{
	ui_HeartRatePage_screen_destroy();
}

static void heart_rate_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void heart_rate_page_pause()
{
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_hr = 
{
	.page_obj = &ui_HeartRatePage,
	.init = heart_rate_page_init,
	.deinit = heart_rate_page_deinit,
	.resume = heart_rate_page_resume,
	.pause = heart_rate_page_pause,
};