// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: MenuPage

#include "ui_MenuPage.h"

lv_obj_t * ui_MenuPage = NULL;
lv_obj_t * ui_MenuEnvPanel = NULL;
lv_obj_t * ui_MenuEnvLabel = NULL;
lv_obj_t * ui_MenuEnvButton = NULL;
lv_obj_t * ui_EnvIconLabel = NULL;
lv_obj_t * ui_MenuHeartRatePanel = NULL;
lv_obj_t * ui_MenuHeartRateLabel = NULL;
lv_obj_t * ui_MenuHeartRateButton = NULL;
lv_obj_t * ui_HeartRateIconLabel = NULL;
lv_obj_t * ui_MenuSportPanel = NULL;
lv_obj_t * ui_MenuSportLabel = NULL;
lv_obj_t * ui_MenuSportButton = NULL;
lv_obj_t * ui_SportIconLabel = NULL;
lv_obj_t * ui_MenuO2Panel = NULL;
lv_obj_t * ui_MenuO2Label = NULL;
lv_obj_t * ui_MenuO2Button = NULL;
lv_obj_t * ui_O2IconLabel = NULL;
lv_obj_t * ui_MenuCalendarPanel = NULL;
lv_obj_t * ui_MenuCalenderLabel = NULL;
lv_obj_t * ui_MenuCalenderButton = NULL;
lv_obj_t * ui_CalendarIconLabel = NULL;
lv_obj_t * ui_MenuTimPanel = NULL;
lv_obj_t * ui_MenuTimLabel = NULL;
lv_obj_t * ui_MenuTimButton = NULL;
lv_obj_t * ui_TimIconLabel = NULL;
lv_obj_t * ui_MenuCompassPanel = NULL;
lv_obj_t * ui_MenuCompassLabel = NULL;
lv_obj_t * ui_MenuCompassButton = NULL;
lv_obj_t * ui_CompassIconLabel = NULL;
lv_obj_t * ui_MenuGamePanel = NULL;
lv_obj_t * ui_MenuGameLabel = NULL;
lv_obj_t * ui_MenuGameButton = NULL;
lv_obj_t * ui_GameIconLabel = NULL;
lv_obj_t * ui_MenuCalculatorPanel = NULL;
lv_obj_t * ui_MenuCalculatorLabel = NULL;
lv_obj_t * ui_MenuCalculatorButton = NULL;
lv_obj_t * ui_CalculatorIconLabel = NULL;
lv_obj_t * ui_MenuSettingPanel = NULL;
lv_obj_t * ui_MenuSettingLabel = NULL;
lv_obj_t * ui_MenuSettingButton = NULL;
lv_obj_t * ui_SettingIconLabel = NULL;
lv_obj_t * ui_MenuAboutPanel = NULL;
lv_obj_t * ui_MenuAboutLabel = NULL;
lv_obj_t * ui_MenuAboutButton = NULL;
lv_obj_t * ui_AboutIconLabel = NULL;
// event funtions


page_t page_menu = 
{
	 .init = ui_MenuPage_screen_init,
	 .deinit = ui_MenuPage_screen_destroy,
	 .page_obj = &ui_MenuPage
};




// build funtions

void ui_MenuPage_screen_init(void)
{
    ui_MenuPage = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_MenuPage, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MenuPage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_MenuPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuEnvPanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuEnvPanel, 240);
    lv_obj_set_height(ui_MenuEnvPanel, 63);
    lv_obj_set_x(ui_MenuEnvPanel, 17);
    lv_obj_set_y(ui_MenuEnvPanel, -25);
    lv_obj_set_align(ui_MenuEnvPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuEnvPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuEnvPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuEnvPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuEnvPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuEnvPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuEnvPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuEnvPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuEnvPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuEnvLabel = lv_label_create(ui_MenuEnvPanel);
    lv_obj_set_width(ui_MenuEnvLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuEnvLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuEnvLabel, -20);
    lv_obj_set_y(ui_MenuEnvLabel, 0);
    lv_obj_set_align(ui_MenuEnvLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuEnvLabel, "环 境");
    lv_obj_set_style_text_font(ui_MenuEnvLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuEnvButton = lv_button_create(ui_MenuEnvPanel);
    lv_obj_set_width(ui_MenuEnvButton, 40);
    lv_obj_set_height(ui_MenuEnvButton, 40);
    lv_obj_set_align(ui_MenuEnvButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuEnvButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuEnvButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuEnvButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuEnvButton, lv_color_hex(0x009632), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuEnvButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnvIconLabel = lv_label_create(ui_MenuEnvButton);
    lv_obj_set_width(ui_EnvIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnvIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EnvIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnvIconLabel, "");
    lv_obj_set_style_text_font(ui_EnvIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuHeartRatePanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuHeartRatePanel, 240);
    lv_obj_set_height(ui_MenuHeartRatePanel, 63);
    lv_obj_set_x(ui_MenuHeartRatePanel, -1);
    lv_obj_set_y(ui_MenuHeartRatePanel, -2);
    lv_obj_set_align(ui_MenuHeartRatePanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuHeartRatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuHeartRatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuHeartRatePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuHeartRatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuHeartRatePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuHeartRatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuHeartRatePanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuHeartRatePanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuHeartRateLabel = lv_label_create(ui_MenuHeartRatePanel);
    lv_obj_set_width(ui_MenuHeartRateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuHeartRateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuHeartRateLabel, -20);
    lv_obj_set_y(ui_MenuHeartRateLabel, 0);
    lv_obj_set_align(ui_MenuHeartRateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuHeartRateLabel, "心 率");
    lv_obj_set_style_text_font(ui_MenuHeartRateLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuHeartRateButton = lv_button_create(ui_MenuHeartRatePanel);
    lv_obj_set_width(ui_MenuHeartRateButton, 40);
    lv_obj_set_height(ui_MenuHeartRateButton, 40);
    lv_obj_set_align(ui_MenuHeartRateButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuHeartRateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuHeartRateButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuHeartRateButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuHeartRateButton, lv_color_hex(0xCC0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuHeartRateButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartRateIconLabel = lv_label_create(ui_MenuHeartRateButton);
    lv_obj_set_width(ui_HeartRateIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HeartRateIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartRateIconLabel, "");
    lv_obj_set_style_text_font(ui_HeartRateIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuSportPanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuSportPanel, 240);
    lv_obj_set_height(ui_MenuSportPanel, 63);
    lv_obj_set_x(ui_MenuSportPanel, -1);
    lv_obj_set_y(ui_MenuSportPanel, -2);
    lv_obj_set_align(ui_MenuSportPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuSportPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuSportPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuSportPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuSportPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuSportPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuSportPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuSportPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuSportPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuSportLabel = lv_label_create(ui_MenuSportPanel);
    lv_obj_set_width(ui_MenuSportLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuSportLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuSportLabel, -20);
    lv_obj_set_y(ui_MenuSportLabel, 0);
    lv_obj_set_align(ui_MenuSportLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuSportLabel, "运 动");
    lv_obj_set_style_text_font(ui_MenuSportLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuSportButton = lv_button_create(ui_MenuSportPanel);
    lv_obj_set_width(ui_MenuSportButton, 40);
    lv_obj_set_height(ui_MenuSportButton, 40);
    lv_obj_set_align(ui_MenuSportButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuSportButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuSportButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuSportButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuSportButton, lv_color_hex(0x009381), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuSportButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportIconLabel = lv_label_create(ui_MenuSportButton);
    lv_obj_set_width(ui_SportIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SportIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SportIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SportIconLabel, "");
    lv_obj_set_style_text_font(ui_SportIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuO2Panel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuO2Panel, 240);
    lv_obj_set_height(ui_MenuO2Panel, 63);
    lv_obj_set_x(ui_MenuO2Panel, -1);
    lv_obj_set_y(ui_MenuO2Panel, -2);
    lv_obj_set_align(ui_MenuO2Panel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuO2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuO2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuO2Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuO2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuO2Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuO2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuO2Panel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuO2Panel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuO2Label = lv_label_create(ui_MenuO2Panel);
    lv_obj_set_width(ui_MenuO2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuO2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuO2Label, -20);
    lv_obj_set_y(ui_MenuO2Label, 0);
    lv_obj_set_align(ui_MenuO2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuO2Label, "血 氧");
    lv_obj_set_style_text_font(ui_MenuO2Label, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuO2Button = lv_button_create(ui_MenuO2Panel);
    lv_obj_set_width(ui_MenuO2Button, 40);
    lv_obj_set_height(ui_MenuO2Button, 40);
    lv_obj_set_align(ui_MenuO2Button, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuO2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuO2Button, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuO2Button, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuO2Button, lv_color_hex(0x007FFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuO2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O2IconLabel = lv_label_create(ui_MenuO2Button);
    lv_obj_set_width(ui_O2IconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O2IconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_O2IconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O2IconLabel, "");
    lv_obj_set_style_text_font(ui_O2IconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuCalendarPanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuCalendarPanel, 240);
    lv_obj_set_height(ui_MenuCalendarPanel, 63);
    lv_obj_set_x(ui_MenuCalendarPanel, -1);
    lv_obj_set_y(ui_MenuCalendarPanel, -2);
    lv_obj_set_align(ui_MenuCalendarPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuCalendarPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuCalendarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCalendarPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuCalendarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuCalendarPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuCalendarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCalendarPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuCalendarPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuCalenderLabel = lv_label_create(ui_MenuCalendarPanel);
    lv_obj_set_width(ui_MenuCalenderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuCalenderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuCalenderLabel, -20);
    lv_obj_set_y(ui_MenuCalenderLabel, 0);
    lv_obj_set_align(ui_MenuCalenderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuCalenderLabel, "日 历");
    lv_obj_set_style_text_font(ui_MenuCalenderLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuCalenderButton = lv_button_create(ui_MenuCalendarPanel);
    lv_obj_set_width(ui_MenuCalenderButton, 40);
    lv_obj_set_height(ui_MenuCalenderButton, 40);
    lv_obj_set_align(ui_MenuCalenderButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuCalenderButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuCalenderButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuCalenderButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCalenderButton, lv_color_hex(0xFF8080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuCalenderButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalendarIconLabel = lv_label_create(ui_MenuCalenderButton);
    lv_obj_set_width(ui_CalendarIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalendarIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalendarIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalendarIconLabel, "");
    lv_obj_set_style_text_font(ui_CalendarIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuTimPanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuTimPanel, 240);
    lv_obj_set_height(ui_MenuTimPanel, 63);
    lv_obj_set_x(ui_MenuTimPanel, -1);
    lv_obj_set_y(ui_MenuTimPanel, -2);
    lv_obj_set_align(ui_MenuTimPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuTimPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuTimPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuTimPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuTimPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuTimPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuTimPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuTimPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuTimPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuTimLabel = lv_label_create(ui_MenuTimPanel);
    lv_obj_set_width(ui_MenuTimLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuTimLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuTimLabel, -20);
    lv_obj_set_y(ui_MenuTimLabel, 0);
    lv_obj_set_align(ui_MenuTimLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuTimLabel, "秒 表");
    lv_obj_set_style_text_font(ui_MenuTimLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuTimButton = lv_button_create(ui_MenuTimPanel);
    lv_obj_set_width(ui_MenuTimButton, 40);
    lv_obj_set_height(ui_MenuTimButton, 40);
    lv_obj_set_align(ui_MenuTimButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuTimButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuTimButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuTimButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuTimButton, lv_color_hex(0xDE81E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuTimButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimIconLabel = lv_label_create(ui_MenuTimButton);
    lv_obj_set_width(ui_TimIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimIconLabel, "");
    lv_obj_set_style_text_font(ui_TimIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuCompassPanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuCompassPanel, 240);
    lv_obj_set_height(ui_MenuCompassPanel, 63);
    lv_obj_set_x(ui_MenuCompassPanel, -1);
    lv_obj_set_y(ui_MenuCompassPanel, -2);
    lv_obj_set_align(ui_MenuCompassPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuCompassPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuCompassPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCompassPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuCompassPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuCompassPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuCompassPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCompassPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuCompassPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuCompassLabel = lv_label_create(ui_MenuCompassPanel);
    lv_obj_set_width(ui_MenuCompassLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuCompassLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuCompassLabel, -14);
    lv_obj_set_y(ui_MenuCompassLabel, 0);
    lv_obj_set_align(ui_MenuCompassLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuCompassLabel, "指南针");
    lv_obj_set_style_text_font(ui_MenuCompassLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuCompassButton = lv_button_create(ui_MenuCompassPanel);
    lv_obj_set_width(ui_MenuCompassButton, 40);
    lv_obj_set_height(ui_MenuCompassButton, 40);
    lv_obj_set_align(ui_MenuCompassButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuCompassButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuCompassButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuCompassButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCompassButton, lv_color_hex(0x830083), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuCompassButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassIconLabel = lv_label_create(ui_MenuCompassButton);
    lv_obj_set_width(ui_CompassIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CompassIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompassIconLabel, "");
    lv_obj_set_style_text_font(ui_CompassIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuGamePanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuGamePanel, 240);
    lv_obj_set_height(ui_MenuGamePanel, 63);
    lv_obj_set_x(ui_MenuGamePanel, -1);
    lv_obj_set_y(ui_MenuGamePanel, -2);
    lv_obj_set_align(ui_MenuGamePanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuGamePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuGamePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuGamePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuGamePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuGamePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuGamePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuGamePanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuGamePanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuGameLabel = lv_label_create(ui_MenuGamePanel);
    lv_obj_set_width(ui_MenuGameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuGameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuGameLabel, -20);
    lv_obj_set_y(ui_MenuGameLabel, 0);
    lv_obj_set_align(ui_MenuGameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuGameLabel, "游 戏");
    lv_obj_set_style_text_font(ui_MenuGameLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuGameButton = lv_button_create(ui_MenuGamePanel);
    lv_obj_set_width(ui_MenuGameButton, 40);
    lv_obj_set_height(ui_MenuGameButton, 40);
    lv_obj_set_align(ui_MenuGameButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuGameButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuGameButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuGameButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuGameButton, lv_color_hex(0xC57110), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuGameButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameIconLabel = lv_label_create(ui_MenuGameButton);
    lv_obj_set_width(ui_GameIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GameIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GameIconLabel, "");
    lv_obj_set_style_text_font(ui_GameIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuCalculatorPanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuCalculatorPanel, 240);
    lv_obj_set_height(ui_MenuCalculatorPanel, 63);
    lv_obj_set_x(ui_MenuCalculatorPanel, -1);
    lv_obj_set_y(ui_MenuCalculatorPanel, -2);
    lv_obj_set_align(ui_MenuCalculatorPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuCalculatorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuCalculatorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCalculatorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuCalculatorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuCalculatorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuCalculatorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCalculatorPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuCalculatorPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuCalculatorLabel = lv_label_create(ui_MenuCalculatorPanel);
    lv_obj_set_width(ui_MenuCalculatorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuCalculatorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuCalculatorLabel, -14);
    lv_obj_set_y(ui_MenuCalculatorLabel, 0);
    lv_obj_set_align(ui_MenuCalculatorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuCalculatorLabel, "计算器");
    lv_obj_set_style_text_font(ui_MenuCalculatorLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuCalculatorButton = lv_button_create(ui_MenuCalculatorPanel);
    lv_obj_set_width(ui_MenuCalculatorButton, 40);
    lv_obj_set_height(ui_MenuCalculatorButton, 40);
    lv_obj_set_align(ui_MenuCalculatorButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuCalculatorButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuCalculatorButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuCalculatorButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuCalculatorButton, lv_color_hex(0x836518), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuCalculatorButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalculatorIconLabel = lv_label_create(ui_MenuCalculatorButton);
    lv_obj_set_width(ui_CalculatorIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalculatorIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalculatorIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalculatorIconLabel, "");
    lv_obj_set_style_text_font(ui_CalculatorIconLabel, &ui_font_MPiconfont25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuSettingPanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuSettingPanel, 240);
    lv_obj_set_height(ui_MenuSettingPanel, 63);
    lv_obj_set_x(ui_MenuSettingPanel, -1);
    lv_obj_set_y(ui_MenuSettingPanel, -2);
    lv_obj_set_align(ui_MenuSettingPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuSettingPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuSettingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuSettingPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuSettingPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuSettingPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuSettingPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuSettingPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuSettingPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuSettingLabel = lv_label_create(ui_MenuSettingPanel);
    lv_obj_set_width(ui_MenuSettingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuSettingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuSettingLabel, -20);
    lv_obj_set_y(ui_MenuSettingLabel, 0);
    lv_obj_set_align(ui_MenuSettingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuSettingLabel, "设 置");
    lv_obj_set_style_text_font(ui_MenuSettingLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuSettingButton = lv_button_create(ui_MenuSettingPanel);
    lv_obj_set_width(ui_MenuSettingButton, 40);
    lv_obj_set_height(ui_MenuSettingButton, 40);
    lv_obj_set_align(ui_MenuSettingButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuSettingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuSettingButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuSettingButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuSettingButton, lv_color_hex(0x708090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuSettingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingIconLabel = lv_label_create(ui_MenuSettingButton);
    lv_obj_set_width(ui_SettingIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingIconLabel, "");
    lv_obj_set_style_text_font(ui_SettingIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuAboutPanel = lv_obj_create(ui_MenuPage);
    lv_obj_set_width(ui_MenuAboutPanel, 240);
    lv_obj_set_height(ui_MenuAboutPanel, 63);
    lv_obj_set_x(ui_MenuAboutPanel, -1);
    lv_obj_set_y(ui_MenuAboutPanel, -2);
    lv_obj_set_align(ui_MenuAboutPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MenuAboutPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuAboutPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuAboutPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuAboutPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuAboutPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuAboutPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuAboutPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MenuAboutPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuAboutLabel = lv_label_create(ui_MenuAboutPanel);
    lv_obj_set_width(ui_MenuAboutLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuAboutLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuAboutLabel, -20);
    lv_obj_set_y(ui_MenuAboutLabel, 0);
    lv_obj_set_align(ui_MenuAboutLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuAboutLabel, "关 于");
    lv_obj_set_style_text_font(ui_MenuAboutLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuAboutButton = lv_button_create(ui_MenuAboutPanel);
    lv_obj_set_width(ui_MenuAboutButton, 40);
    lv_obj_set_height(ui_MenuAboutButton, 40);
    lv_obj_set_align(ui_MenuAboutButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MenuAboutButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuAboutButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuAboutButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuAboutButton, lv_color_hex(0x2F4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuAboutButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutIconLabel = lv_label_create(ui_MenuAboutButton);
    lv_obj_set_width(ui_AboutIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AboutIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AboutIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AboutIconLabel, "");
    lv_obj_set_style_text_font(ui_AboutIconLabel, &ui_font_MPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MenuPage_screen_destroy(void)
{
	
}
