// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: TimerPage

#include "ui_TimerPage.h"

lv_obj_t * ui_TimerPage = NULL;
lv_obj_t * ui_StartButton = NULL;
lv_obj_t * ui_StartIconLabel = NULL;
lv_obj_t * ui_ReButton = NULL;
lv_obj_t * ui_ReIconLabel = NULL;
lv_obj_t * ui_TimerMinLabel = NULL;
lv_obj_t * ui_TimerColonLabel = NULL;
lv_obj_t * ui_TimerSecLabel = NULL;
lv_obj_t * ui_TimerPointLabel = NULL;
lv_obj_t * ui_TimerMilSecLabel = NULL;

lv_obj_t*  scale = NULL; //刻度盘
// event funtions

/* 页面回调函数 */
static void timer_page_event_cb(lv_event_t* e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_GESTURE)
	{
			lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
			if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
      {
				 page_back();
      }
	}
}

/* 启动按钮回调函数 */
static void start_btn_event_cb(lv_event_t* e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_VALUE_CHANGED) // 检测到
	{
		 if(lv_obj_has_state(target,LV_STATE_CHECKED))
		 {
				lv_label_set_text(ui_StartIconLabel, ""); // 按下后变为暂停图标
		 }
		 else
		 {
			  lv_label_set_text(ui_StartIconLabel, ""); // 按下后变为启动图标
		 }
	}
}

/* 刷新按钮回调函数 */
static void refresh_btn_event_cb(lv_event_t* e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t * target = lv_event_get_target(e);
	
	if(event_code == LV_EVENT_GESTURE)
	{
			lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
			if(dir == LV_DIR_RIGHT) // 从输入检测手势向右滑动
      {
				 page_back();
      }
	}
}

// build funtions
void ui_TimerPage_screen_init(void)
{
    ui_TimerPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TimerPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

		scale = lv_scale_create(ui_TimerPage);
    lv_obj_set_size(scale, 240, 240);
    lv_obj_center(scale); //居中到父对象

    // 设置刻度盘:LV_PART_MAIN
    lv_obj_set_style_bg_opa(scale, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_bg_color(scale, lv_color_hex(0x292831), LV_PART_MAIN); //灰色背景
    lv_obj_set_style_radius(scale, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    lv_obj_set_style_clip_corner(scale, true, LV_PART_MAIN); // 圆角裁剪
    //lv_obj_set_style_pad_all(scale, 15, LV_PART_MAIN); // 是否需要填充外侧

    // 刻度线在内部
    lv_scale_set_mode(scale, LV_SCALE_MODE_ROUND_INNER);

    // 刻度设置
    lv_scale_set_total_tick_count(scale, 61);   // 设置刻度总数(大小刻度都包括)：0..60,共61个刻度
    lv_scale_set_major_tick_every(scale, 0);  // 设置大刻度出现频率，0代表不区分主刻度
    lv_scale_set_label_show(scale, false);      // 刻度不显示数字
    lv_scale_set_angle_range(scale, 360);       // 全圆
    //lv_scale_set_rotation(scale, -90);          // 刻度从最上方12点开始

    // 刻度线样式设置：LV_PART_ITEMS
    lv_obj_set_style_line_color(scale,lv_palette_main(LV_PALETTE_BLUE), LV_PART_ITEMS);
    lv_obj_set_style_line_width(scale, 2, LV_PART_ITEMS); // 刻度线宽度为2
    lv_obj_set_style_line_opa(scale, LV_OPA_COVER, LV_PART_ITEMS);
    lv_obj_set_style_length(scale, 10,LV_PART_ITEMS); // 刻度线长度为10
	
	
    ui_StartButton = lv_button_create(ui_TimerPage);
    lv_obj_set_width(ui_StartButton, 60);
    lv_obj_set_height(ui_StartButton, 60);
    lv_obj_set_x(ui_StartButton, 40);
    lv_obj_set_y(ui_StartButton, 50);
    lv_obj_set_align(ui_StartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StartButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartIconLabel = lv_label_create(ui_StartButton);
    lv_obj_set_width(ui_StartIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartIconLabel, 0);
    lv_obj_set_y(ui_StartIconLabel, 0);
    lv_obj_set_align(ui_StartIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartIconLabel, "");
    lv_obj_set_style_text_font(ui_StartIconLabel, &ui_font_TMPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReButton = lv_button_create(ui_TimerPage);
    lv_obj_set_width(ui_ReButton, 60);
    lv_obj_set_height(ui_ReButton, 60);
    lv_obj_set_x(ui_ReButton, -40);
    lv_obj_set_y(ui_ReButton, 50);
    lv_obj_set_align(ui_ReButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ReButton, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReIconLabel = lv_label_create(ui_ReButton);
    lv_obj_set_width(ui_ReIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReIconLabel, "");
    lv_obj_set_style_text_font(ui_ReIconLabel, &ui_font_TMPiconfont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerMinLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerMinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerMinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerMinLabel, -69);
    lv_obj_set_y(ui_TimerMinLabel, -20);
    lv_obj_set_align(ui_TimerMinLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerMinLabel, "00");
    lv_obj_set_style_text_font(ui_TimerMinLabel, &ui_font_CuYuan45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerColonLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerColonLabel, -32);
    lv_obj_set_y(ui_TimerColonLabel, -24);
    lv_obj_set_align(ui_TimerColonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerColonLabel, ":");
    lv_obj_set_style_text_font(ui_TimerColonLabel, &ui_font_CuYuan45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerSecLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerSecLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerSecLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerSecLabel, 6);
    lv_obj_set_y(ui_TimerSecLabel, -20);
    lv_obj_set_align(ui_TimerSecLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerSecLabel, "00");
    lv_obj_set_style_text_font(ui_TimerSecLabel, &ui_font_CuYuan45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerPointLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerPointLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerPointLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerPointLabel, 38);
    lv_obj_set_y(ui_TimerPointLabel, -20);
    lv_obj_set_align(ui_TimerPointLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerPointLabel, ".");
    lv_obj_set_style_text_font(ui_TimerPointLabel, &ui_font_CuYuan45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerMilSecLabel = lv_label_create(ui_TimerPage);
    lv_obj_set_width(ui_TimerMilSecLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerMilSecLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerMilSecLabel, 71);
    lv_obj_set_y(ui_TimerMilSecLabel, -20);
    lv_obj_set_align(ui_TimerMilSecLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerMilSecLabel, "00");
    lv_obj_set_style_text_font(ui_TimerMilSecLabel, &ui_font_CuYuan45, LV_PART_MAIN | LV_STATE_DEFAULT);
		
		lv_obj_add_event_cb(ui_TimerPage,timer_page_event_cb,LV_EVENT_GESTURE,NULL);
		
    lv_obj_add_event_cb(ui_StartButton, start_btn_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_ReButton, refresh_btn_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
}

void ui_TimerPage_screen_destroy(void)
{
    if(ui_TimerPage) lv_obj_del(ui_TimerPage);

    // NULL screen variables
    ui_TimerPage = NULL;
    ui_StartButton = NULL;
    ui_StartIconLabel = NULL;
    ui_ReButton = NULL;
    ui_ReIconLabel = NULL;
    ui_TimerMinLabel = NULL;
    ui_TimerColonLabel = NULL;
    ui_TimerSecLabel = NULL;
    ui_TimerPointLabel = NULL;
    ui_TimerMilSecLabel = NULL;

}


static void timer_page_init()
{
	ui_TimerPage_screen_init();
}

static void timer_page_deinit()
{
	ui_TimerPage_screen_destroy();
}

static void timer_page_resume() 
{
    // 保留：页面切换回来时刷新显示内容、重启动画、恢复定时器等。
}


static void timer_page_pause()
{
	  // 保留：页面切换离开时暂停动画、停止定时器、保存页面状态等。
}

page_t page_timer = 
{
	.page_obj = &ui_TimerPage,
	.init = timer_page_init,
	.deinit = timer_page_deinit,
	.resume = timer_page_resume,
	.pause = timer_page_pause,
};