// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: testpage

#ifndef _TESTPAGE_UI_H
#define _TESTPAGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "../Utils/Inc/page_manager.h"

///////////////////// SCREENS ////////////////////

#include "screens/Inc/ui_HomePage.h"
#include "screens/Inc/ui_MenuPage.h"
///////////////////// VARIABLES ////////////////////


// EVENTS

//extern lv_obj_t * ui____initial_actions0;

// FONTS£º ×¢²á×ÖÌå
LV_FONT_DECLARE(ui_font_ALiDaKai20);
LV_FONT_DECLARE(ui_font_CuYuan20);
LV_FONT_DECLARE(ui_font_CuYuan30);
LV_FONT_DECLARE(ui_font_CuYuan40);
LV_FONT_DECLARE(ui_font_CuYuan60);
LV_FONT_DECLARE(ui_font_OpenSasnsItalic15);
LV_FONT_DECLARE(ui_font_OpenSasnsItalic100);

LV_FONT_DECLARE(ui_font_HPiconfont25);
LV_FONT_DECLARE(ui_font_MPiconfont25);
LV_FONT_DECLARE(ui_font_MPiconfont30);
LV_FONT_DECLARE(ui_font_EPiconfont30);
LV_FONT_DECLARE(ui_font_HRPiconfont50);
LV_FONT_DECLARE(ui_font_O2MPiconfont50);
LV_FONT_DECLARE(ui_font_TMPiconfont30);
LV_FONT_DECLARE(ui_font_CPiconfont28);
LV_FONT_DECLARE(ui_font_SPiconfont30);
LV_FONT_DECLARE(ui_font_LTSiconfont40);

// UI INIT
void ui_init(void);
//void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
