// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: AboutPage

#include "../ui.h"

lv_obj_t * ui_AboutPage = NULL;
lv_obj_t * ui_NameLabel = NULL;
lv_obj_t * ui_NameTextLabel = NULL;
lv_obj_t * ui_VersionLabel = NULL;
lv_obj_t * ui_VersionTextLabel = NULL;
lv_obj_t * ui_MCULabel = NULL;
lv_obj_t * ui_MCUTextLabel = NULL;
lv_obj_t * ui_OSLabel = NULL;
lv_obj_t * ui_OSTextLabel = NULL;
lv_obj_t * ui_UILabel = NULL;
lv_obj_t * ui_UITextLabel = NULL;
// event funtions

// build funtions

void ui_AboutPage_screen_init(void)
{
    ui_AboutPage = lv_obj_create(NULL);

    ui_NameLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_NameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameLabel, 10);
    lv_obj_set_y(ui_NameLabel, 10);
    lv_label_set_text(ui_NameLabel, "手表型号");
    lv_obj_set_style_text_color(ui_NameLabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameTextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_NameTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTextLabel, 15);
    lv_obj_set_y(ui_NameTextLabel, 35);
    lv_label_set_text(ui_NameTextLabel, "SWatch");
    lv_obj_set_style_text_font(ui_NameTextLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_VersionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionLabel, 10);
    lv_obj_set_y(ui_VersionLabel, 60);
    lv_label_set_text(ui_VersionLabel, "固件版本");
    lv_obj_set_style_text_color(ui_VersionLabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VersionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VersionLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionTextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_VersionTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionTextLabel, 15);
    lv_obj_set_y(ui_VersionTextLabel, 85);
    lv_label_set_text(ui_VersionTextLabel, "V1.0.0");
    lv_obj_set_style_text_font(ui_VersionTextLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MCULabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_MCULabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MCULabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MCULabel, 10);
    lv_obj_set_y(ui_MCULabel, 110);
    lv_label_set_text(ui_MCULabel, "主控芯片");
    lv_obj_set_style_text_color(ui_MCULabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MCULabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MCULabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MCUTextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_MCUTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MCUTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MCUTextLabel, 15);
    lv_obj_set_y(ui_MCUTextLabel, 135);
    lv_label_set_text(ui_MCUTextLabel, "STM32F411CEU6");
    lv_obj_set_style_text_font(ui_MCUTextLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OSLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_OSLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OSLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OSLabel, 10);
    lv_obj_set_y(ui_OSLabel, 160);
    lv_label_set_text(ui_OSLabel, "操作系统");
    lv_obj_set_style_text_color(ui_OSLabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OSLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OSLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OSTextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_OSTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OSTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OSTextLabel, 15);
    lv_obj_set_y(ui_OSTextLabel, 185);
    lv_label_set_text(ui_OSTextLabel, "FreeRTOS");
    lv_obj_set_style_text_font(ui_OSTextLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UILabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_UILabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UILabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UILabel, 10);
    lv_obj_set_y(ui_UILabel, 210);
    lv_label_set_text(ui_UILabel, "图形界面");
    lv_obj_set_style_text_color(ui_UILabel, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UILabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UILabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UITextLabel = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_UITextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UITextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UITextLabel, 15);
    lv_obj_set_y(ui_UITextLabel, 235);
    lv_label_set_text(ui_UITextLabel, "LVGL");
    lv_obj_set_style_text_font(ui_UITextLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_AboutPage_screen_destroy(void)
{
    if(ui_AboutPage) lv_obj_del(ui_AboutPage);

    // NULL screen variables
    ui_AboutPage = NULL;
    ui_NameLabel = NULL;
    ui_NameTextLabel = NULL;
    ui_VersionLabel = NULL;
    ui_VersionTextLabel = NULL;
    ui_MCULabel = NULL;
    ui_MCUTextLabel = NULL;
    ui_OSLabel = NULL;
    ui_OSTextLabel = NULL;
    ui_UILabel = NULL;
    ui_UITextLabel = NULL;

}
