// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SpO2MeasurePage

#include "../ui.h"

lv_obj_t * ui_SpO2MeasurePage = NULL;
lv_obj_t * ui_SpO2IconLabel = NULL;
lv_obj_t * ui_SpO2NumLabel = NULL;
lv_obj_t * ui_PercentLabel = NULL;
lv_obj_t * ui_MeasureLabel = NULL;
// event funtions

// build funtions

void ui_SpO2MeasurePage_screen_init(void)
{
    ui_SpO2MeasurePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SpO2MeasurePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpO2IconLabel = lv_label_create(ui_SpO2MeasurePage);
    lv_obj_set_width(ui_SpO2IconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpO2IconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpO2IconLabel, 0);
    lv_obj_set_y(ui_SpO2IconLabel, -84);
    lv_obj_set_align(ui_SpO2IconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpO2IconLabel, "");
    lv_obj_set_style_text_color(ui_SpO2IconLabel, lv_color_hex(0x0081FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpO2IconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpO2IconLabel, &ui_font_O2MPiconfont50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpO2NumLabel = lv_label_create(ui_SpO2MeasurePage);
    lv_obj_set_width(ui_SpO2NumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpO2NumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpO2NumLabel, -4);
    lv_obj_set_y(ui_SpO2NumLabel, 0);
    lv_obj_set_align(ui_SpO2NumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpO2NumLabel, "99");
    lv_obj_set_style_text_font(ui_SpO2NumLabel, &ui_font_CuYuan60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PercentLabel = lv_label_create(ui_SpO2MeasurePage);
    lv_obj_set_width(ui_PercentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentLabel, 84);
    lv_obj_set_y(ui_PercentLabel, 12);
    lv_obj_set_align(ui_PercentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PercentLabel, "%");
    lv_obj_set_style_text_font(ui_PercentLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeasureLabel = lv_label_create(ui_SpO2MeasurePage);
    lv_obj_set_width(ui_MeasureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureLabel, 4);
    lv_obj_set_y(ui_MeasureLabel, 79);
    lv_obj_set_align(ui_MeasureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureLabel, "正在测量...");
    lv_obj_set_style_text_color(ui_MeasureLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_SpO2MeasurePage_screen_destroy(void)
{
    if(ui_SpO2MeasurePage) lv_obj_del(ui_SpO2MeasurePage);

    // NULL screen variables
    ui_SpO2MeasurePage = NULL;
    ui_SpO2IconLabel = NULL;
    ui_SpO2NumLabel = NULL;
    ui_PercentLabel = NULL;
    ui_MeasureLabel = NULL;

}
