// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LTSetPage_screen_init();
    ui_SOffTimeSetPage_screen_init();
    ui_DateTimeMenuPage_screen_init();
    ui_DateSetPage_screen_init();
    ui_TimeSetPage_screen_init();
    ui_AllSettingPages_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LTSetPage);
}

void ui_destroy(void)
{
    ui_LTSetPage_screen_destroy();
    ui_SOffTimeSetPage_screen_destroy();
    ui_DateTimeMenuPage_screen_destroy();
    ui_DateSetPage_screen_destroy();
    ui_TimeSetPage_screen_destroy();
    ui_AllSettingPages_screen_destroy();
}
