// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: LightTimePage

#ifndef _LIGHTTIMEPAGE_UI_H
#define _LIGHTTIMEPAGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_LTSetPage.h"
#include "screens/ui_SOffTimeSetPage.h"
#include "screens/ui_DateTimeMenuPage.h"
#include "screens/ui_DateSetPage.h"
#include "screens/ui_TimeSetPage.h"
#include "screens/ui_AllSettingPages.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_CuYuan40);
LV_FONT_DECLARE(ui_font_LTSiconfont40);
LV_FONT_DECLARE(ui_font_ALiDaKai20);
LV_FONT_DECLARE(ui_font_CuYuan20);
LV_FONT_DECLARE(ui_font_CuYuan30);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
