// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: HeartRatePage

#include "../ui.h"

lv_obj_t * ui_HeartRatePage = NULL;
lv_obj_t * ui_HeartRateIconLabel = NULL;
lv_obj_t * ui_TimesLabel = NULL;
lv_obj_t * ui_HeartRateNumLabel = NULL;
lv_obj_t * ui_MeasureLabel = NULL;
// event funtions

// build funtions

void ui_HeartRatePage_screen_init(void)
{
    ui_HeartRatePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HeartRatePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeartRateIconLabel = lv_label_create(ui_HeartRatePage);
    lv_obj_set_width(ui_HeartRateIconLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateIconLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRateIconLabel, 0);
    lv_obj_set_y(ui_HeartRateIconLabel, -84);
    lv_obj_set_align(ui_HeartRateIconLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartRateIconLabel, "");
    lv_obj_set_style_text_color(ui_HeartRateIconLabel, lv_color_hex(0xD81E06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeartRateIconLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeartRateIconLabel, &ui_font_HRPiconfont50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimesLabel = lv_label_create(ui_HeartRatePage);
    lv_obj_set_width(ui_TimesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimesLabel, 84);
    lv_obj_set_y(ui_TimesLabel, 12);
    lv_obj_set_align(ui_TimesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimesLabel, "次/分");
    lv_obj_set_style_text_color(ui_TimesLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimesLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimesLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartRateNumLabel = lv_label_create(ui_HeartRatePage);
    lv_obj_set_width(ui_HeartRateNumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateNumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRateNumLabel, -2);
    lv_obj_set_y(ui_HeartRateNumLabel, 3);
    lv_obj_set_align(ui_HeartRateNumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartRateNumLabel, "100");
    lv_obj_set_style_text_font(ui_HeartRateNumLabel, &ui_font_CuYuan60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeasureLabel = lv_label_create(ui_HeartRatePage);
    lv_obj_set_width(ui_MeasureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureLabel, 4);
    lv_obj_set_y(ui_MeasureLabel, 79);
    lv_obj_set_align(ui_MeasureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureLabel, "正在测量...");
    lv_obj_set_style_text_color(ui_MeasureLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureLabel, &ui_font_ALiDaKai20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_HeartRatePage_screen_destroy(void)
{
    if(ui_HeartRatePage) lv_obj_del(ui_HeartRatePage);

    // NULL screen variables
    ui_HeartRatePage = NULL;
    ui_HeartRateIconLabel = NULL;
    ui_TimesLabel = NULL;
    ui_HeartRateNumLabel = NULL;
    ui_MeasureLabel = NULL;

}
