// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: HeartRatePage

#ifndef UI_HEARTRATEPAGE_H
#define UI_HEARTRATEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HeartRatePage
extern void ui_HeartRatePage_screen_init(void);
extern void ui_HeartRatePage_screen_destroy(void);
extern lv_obj_t * ui_HeartRatePage;
extern lv_obj_t * ui_HeartRateIconLabel;
extern lv_obj_t * ui_TimesLabel;
extern lv_obj_t * ui_HeartRateNumLabel;
extern lv_obj_t * ui_MeasureLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

