// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: CalendarPage

#include "../ui.h"

lv_obj_t * ui_CalendarPage = NULL;
lv_obj_t * ui_Calendar = NULL;
// event funtions

// build funtions

void ui_CalendarPage_screen_init(void)
{
    ui_CalendarPage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CalendarPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar = lv_calendar_create(ui_CalendarPage);
    lv_calendar_set_today_date(ui_Calendar, 2025, 8, 15);
    lv_calendar_set_showed_date(ui_Calendar, 2025, 8);
    lv_obj_t * ui_Calendar_header = lv_calendar_header_arrow_create(ui_Calendar);
    lv_obj_set_width(ui_Calendar, 240);
    lv_obj_set_height(ui_Calendar, 280);
    lv_obj_set_align(ui_Calendar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_CalendarPage_screen_destroy(void)
{
    if(ui_CalendarPage) lv_obj_del(ui_CalendarPage);

    // NULL screen variables
    ui_CalendarPage = NULL;
    ui_Calendar = NULL;

}
