// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: MenuPage

#ifndef UI_MENUPAGE_H
#define UI_MENUPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"

// SCREEN: ui_MenuPage
extern void ui_MenuPage_screen_init(void);
extern void ui_MenuPage_screen_destroy(void);
extern lv_obj_t * ui_MenuPage;
extern lv_obj_t * ui_MenuEnvPanel;
extern lv_obj_t * ui_MenuEnvLabel;
extern lv_obj_t * ui_MenuEnvButton;
extern lv_obj_t * ui_EnvIconLabel;
extern lv_obj_t * ui_MenuHeartRatePanel;
extern lv_obj_t * ui_MenuHeartRateLabel;
extern lv_obj_t * ui_MenuHeartRateButton;
extern lv_obj_t * ui_HeartRateIconLabel;
extern lv_obj_t * ui_MenuSportPanel;
extern lv_obj_t * ui_MenuSportLabel;
extern lv_obj_t * ui_MenuSportButton;
extern lv_obj_t * ui_SportIconLabel;
extern lv_obj_t * ui_MenuO2Panel;
extern lv_obj_t * ui_MenuO2Label;
extern lv_obj_t * ui_MenuO2Button;
extern lv_obj_t * ui_O2IconLabel;
extern lv_obj_t * ui_MenuCalendarPanel;
extern lv_obj_t * ui_MenuCalenderLabel;
extern lv_obj_t * ui_MenuCalenderButton;
extern lv_obj_t * ui_CalendarIconLabel;
extern lv_obj_t * ui_MenuTimPanel;
extern lv_obj_t * ui_MenuTimLabel;
extern lv_obj_t * ui_MenuTimButton;
extern lv_obj_t * ui_TimIconLabel;
extern lv_obj_t * ui_MenuCompassPanel;
extern lv_obj_t * ui_MenuCompassLabel;
extern lv_obj_t * ui_MenuCompassButton;
extern lv_obj_t * ui_CompassIconLabel;
extern lv_obj_t * ui_MenuGamePanel;
extern lv_obj_t * ui_MenuGameLabel;
extern lv_obj_t * ui_MenuGameButton;
extern lv_obj_t * ui_GameIconLabel;
extern lv_obj_t * ui_MenuCalculatorPanel;
extern lv_obj_t * ui_MenuCalculatorLabel;
extern lv_obj_t * ui_MenuCalculatorButton;
extern lv_obj_t * ui_CalculatorIconLabel;
extern lv_obj_t * ui_MenuSettingPanel;
extern lv_obj_t * ui_MenuSettingLabel;
extern lv_obj_t * ui_MenuSettingButton;
extern lv_obj_t * ui_SettingIconLabel;
extern lv_obj_t * ui_MenuAboutPanel;
extern lv_obj_t * ui_MenuAboutLabel;
extern lv_obj_t * ui_MenuAboutButton;
extern lv_obj_t * ui_AboutIconLabel;
// CUSTOM VARIABLES

extern page_t page_menu; // 菜单页面对象

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

