// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SpO2MeasurePage

#ifndef UI_SPO2MEASUREPAGE_H
#define UI_SPO2MEASUREPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../ui.h"
	
// SCREEN: ui_SpO2MeasurePage
extern void ui_SpO2MeasurePage_screen_init(void);
extern void ui_SpO2MeasurePage_screen_destroy(void);
extern lv_obj_t * ui_SpO2MeasurePage;
extern lv_obj_t * ui_SpO2IconLabel;
extern lv_obj_t * ui_SpO2NumLabel;
extern lv_obj_t * ui_PercentLabel;
extern lv_obj_t * ui_SpO2MeasureLabel;
// CUSTOM VARIABLES

extern page_t page_SpO2;	

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

